"""
CODE COMBAT Pro - Solutions Registry
Stores official, production-verified solutions in Python 3 (Normal), Python 3 (Class Solution),
Java, and C for all 30 problems across Set 1 and Set 2.
"""

from typing import Dict, Any, Optional

SOLUTIONS_REGISTRY: Dict[str, Dict[str, str]] = {
  "two_sum": {
    "python": "n = int(input())\nnums = list(map(int, input().split()))\ntarget = int(input())\n\nm = {}\nfor i, num in enumerate(nums):\n    diff = target - num\n    if diff in m:\n        print(m[diff], i)\n        break\n    m[num] = i\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int[] twoSum(int[] nums, int target) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int comp = target - nums[i];\n            if (map.containsKey(comp)) {\n                return new int[]{map.get(comp), i};\n            }\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int target;\n    scanf(\"%d\", &target);\n\n    for (int i = 0; i < n; i++) {\n        for (int j = i + 1; j < n; j++) {\n            if (nums[i] + nums[j] == target) {\n                printf(\"%d %d\\n\", i, j);\n                return 0;\n            }\n        }\n    }\n    return 0;\n}",
    "python_class": "class Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n        m = {}\n        for i, n in enumerate(nums):\n            comp = target - n\n            if comp in m:\n                return [m[comp], i]\n            m[n] = i\n        return []\n",
  },
  "palindrome_number": {
    "python": "x = int(input())\ns = str(x)\nprint(\"true\" if s == s[::-1] else \"false\")\n",
    "java": "class Solution {\n    public boolean isPalindrome(int x) {\n        if (x < 0) return false;\n        String s = String.valueOf(x);\n        return s.equals(new StringBuilder(s).reverse().toString());\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdbool.h>\n\nint main() {\n    int x;\n    if (scanf(\"%d\", &x) != 1) return 0;\n    if (x < 0) {\n        printf(\"false\\n\");\n        return 0;\n    }\n    long orig = x, rev = 0;\n    while (x > 0) {\n        rev = rev * 10 + (x % 10);\n        x /= 10;\n    }\n    if (orig == rev) printf(\"true\\n\");\n    else printf(\"false\\n\");\n    return 0;\n}",
    "python_class": "class Solution:\n    def isPalindrome(self, x: int) -> bool:\n        if x < 0:\n            return False\n        s = str(x)\n        return s == s[::-1]\n",
  },
  "reverse_string": {
    "python": "s = input().strip()\nprint(s[::-1])\n",
    "java": "class Solution {\n    public String reverseString(String s) {\n        return new StringBuilder(s).reverse().toString();\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100005];\n    if (!fgets(s, sizeof(s), stdin)) return 0;\n    int len = strlen(s);\n    while (len > 0 && (s[len - 1] == '\\n' || s[len - 1] == '\\r')) {\n        s[--len] = '\\0';\n    }\n    for (int i = 0, j = len - 1; i < j; i++, j--) {\n        char t = s[i]; s[i] = s[j]; s[j] = t;\n    }\n    printf(\"%s\\n\", s);\n    return 0;\n}",
    "python_class": "class Solution:\n    def reverseString(self, s: str) -> str:\n        return s[::-1]\n",
  },
  "count_vowels": {
    "python": "s = input().strip()\nvowels = set(\"aeiouAEIOU\")\nprint(sum(1 for c in s if c in vowels))\n",
    "java": "class Solution {\n    public int countVowels(String s) {\n        int count = 0;\n        String v = \"aeiouAEIOU\";\n        for (char c : s.toCharArray()) {\n            if (v.indexOf(c) != -1) count++;\n        }\n        return count;\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n#include <ctype.h>\n\nint main() {\n    char s[100005];\n    if (!fgets(s, sizeof(s), stdin)) return 0;\n    int count = 0;\n    for (int i = 0; s[i]; i++) {\n        char c = tolower(s[i]);\n        if (c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u') count++;\n    }\n    printf(\"%d\\n\", count);\n    return 0;\n}",
    "python_class": "class Solution:\n    def countVowels(self, s: str) -> int:\n        vowels = set(\"aeiouAEIOU\")\n        return sum(1 for c in s if c in vowels)\n",
  },
  "find_maximum": {
    "python": "n = int(input())\nnums = list(map(int, input().split()))\nprint(max(nums))\n",
    "java": "class Solution {\n    public int findMax(int[] nums) {\n        int m = nums[0];\n        for (int x : nums) if (x > m) m = x;\n        return m;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int max = nums[0];\n    for (int i = 1; i < n; i++) {\n        if (nums[i] > max) max = nums[i];\n    }\n    printf(\"%d\\n\", max);\n    return 0;\n}",
    "python_class": "class Solution:\n    def findMax(self, nums: List[int]) -> int:\n        return max(nums) if nums else 0\n",
  },
  "longest_substring": {
    "python": "s = input().strip()\nseen = {}\nleft = 0\nmax_len = 0\nfor right, ch in enumerate(s):\n    if ch in seen and seen[ch] >= left:\n        left = seen[ch] + 1\n    seen[ch] = right\n    max_len = max(max_len, right - left + 1)\nprint(max_len)\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int lengthOfLongestSubstring(String s) {\n        Map<Character, Integer> map = new HashMap<>();\n        int left = 0, maxLen = 0;\n        for (int right = 0; right < s.length(); right++) {\n            char c = s.charAt(right);\n            if (map.containsKey(c) && map.get(c) >= left) {\n                left = map.get(c) + 1;\n            }\n            map.put(c, right);\n            maxLen = Math.max(maxLen, right - left + 1);\n        }\n        return maxLen;\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100005];\n    if (scanf(\"%s\", s) != 1) {\n        printf(\"0\\n\");\n        return 0;\n    }\n    int last[256];\n    for (int i = 0; i < 256; i++) last[i] = -1;\n    int max_len = 0, start = 0;\n    for (int i = 0; s[i]; i++) {\n        unsigned char c = (unsigned char)s[i];\n        if (last[c] >= start) {\n            start = last[c] + 1;\n        }\n        last[c] = i;\n        int cur = i - start + 1;\n        if (cur > max_len) max_len = cur;\n    }\n    printf(\"%d\\n\", max_len);\n    return 0;\n}",
    "python_class": "class Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:\n        seen = {}\n        left = 0\n        max_len = 0\n        for right, ch in enumerate(s):\n            if ch in seen and seen[ch] >= left:\n                left = seen[ch] + 1\n            seen[ch] = right\n            max_len = max(max_len, right - left + 1)\n        return max_len\n",
  },
  "maximum_subarray": {
    "python": "n = int(input())\nnums = list(map(int, input().split()))\nmax_so_far = nums[0]\ncurr = nums[0]\nfor x in nums[1:]:\n    curr = max(x, curr + x)\n    max_so_far = max(max_so_far, curr)\nprint(max_so_far)\n",
    "java": "class Solution {\n    public int maxSubArray(int[] nums) {\n        int cur = nums[0], maxS = nums[0];\n        for (int i = 1; i < nums.length; i++) {\n            cur = Math.max(nums[i], cur + nums[i]);\n            maxS = Math.max(maxS, cur);\n        }\n        return maxS;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    long long max_sum = nums[0], cur_sum = nums[0];\n    for (int i = 1; i < n; i++) {\n        cur_sum = (nums[i] > cur_sum + nums[i]) ? nums[i] : cur_sum + nums[i];\n        if (cur_sum > max_sum) max_sum = cur_sum;\n    }\n    printf(\"%lld\\n\", max_sum);\n    return 0;\n}",
    "python_class": "class Solution:\n    def maxSubArray(self, nums: List[int]) -> int:\n        max_so_far = nums[0]\n        curr = nums[0]\n        for x in nums[1:]:\n            curr = max(x, curr + x)\n            max_so_far = max(max_so_far, curr)\n        return max_so_far\n",
  },
  "merge_intervals": {
    "python": "n = int(input())\nintervals = []\nfor _ in range(n):\n    intervals.append(list(map(int, input().split())))\nintervals.sort(key=lambda x: x[0])\nmerged = [intervals[0]]\nfor cur in intervals[1:]:\n    if cur[0] <= merged[-1][1]:\n        merged[-1][1] = max(merged[-1][1], cur[1])\n    else:\n        merged.append(cur)\nfor start, end in merged:\n    print(start, end)\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int[][] merge(int[][] intervals) {\n        if (intervals.length <= 1) return intervals;\n        Arrays.sort(intervals, (a, b) -> Integer.compare(a[0], b[0]));\n        List<int[]> res = new ArrayList<>();\n        int[] cur = intervals[0];\n        res.add(cur);\n        for (int[] inv : intervals) {\n            if (inv[0] <= cur[1]) {\n                cur[1] = Math.max(cur[1], inv[1]);\n            } else {\n                cur = inv;\n                res.add(cur);\n            }\n        }\n        return res.toArray(new int[res.size()][]);\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct { int start, end; } Interval;\n\nint compare(const void* a, const void* b) {\n    Interval* ia = (Interval*)a;\n    Interval* ib = (Interval*)b;\n    return ia->start - ib->start;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1 || n <= 0) return 0;\n    Interval intervals[n];\n    for (int i = 0; i < n; i++) scanf(\"%d %d\", &intervals[i].start, &intervals[i].end);\n    qsort(intervals, n, sizeof(Interval), compare);\n\n    Interval res[n];\n    int count = 0;\n    res[0] = intervals[0];\n    count = 1;\n\n    for (int i = 1; i < n; i++) {\n        if (intervals[i].start <= res[count - 1].end) {\n            if (intervals[i].end > res[count - 1].end) res[count - 1].end = intervals[i].end;\n        } else {\n            res[count++] = intervals[i];\n        }\n    }\n\n    for (int i = 0; i < count; i++) {\n        printf(\"%d %d\\n\", res[i].start, res[i].end);\n    }\n    return 0;\n}",
    "python_class": "class Solution:\n    def merge(self, intervals: List[List[int]]) -> List[List[int]]:\n        if not intervals:\n            return []\n        intervals.sort(key=lambda x: x[0])\n        merged = [intervals[0]]\n        for cur in intervals[1:]:\n            if cur[0] <= merged[-1][1]:\n                merged[-1][1] = max(merged[-1][1], cur[1])\n            else:\n                merged.append(cur)\n        return merged\n",
  },
  "rotate_array": {
    "python": "n, k = map(int, input().split())\nnums = list(map(int, input().split()))\nk = k % n\nif k > 0:\n    nums = nums[-k:] + nums[:-k]\nprint(' '.join(map(str, nums)))\n",
    "java": "class Solution {\n    public void rotate(int[] nums, int k) {\n        int n = nums.length;\n        if (n == 0) return;\n        k %= n;\n        reverse(nums, 0, n - 1);\n        reverse(nums, 0, k - 1);\n        reverse(nums, k, n - 1);\n    }\n    private void reverse(int[] a, int l, int r) {\n        while (l < r) {\n            int t = a[l]; a[l] = a[r]; a[r] = t;\n            l++; r--;\n        }\n    }\n}",
    "c": "#include <stdio.h>\n\nvoid reverse(int arr[], int l, int r) {\n    while (l < r) {\n        int t = arr[l]; arr[l] = arr[r]; arr[r] = t;\n        l++; r--;\n    }\n}\n\nint main() {\n    int n, k;\n    if (scanf(\"%d %d\", &n, &k) != 2 || n <= 0) return 0;\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    k = k % n;\n\n    reverse(nums, 0, n - 1);\n    reverse(nums, 0, k - 1);\n    reverse(nums, k, n - 1);\n\n    for (int i = 0; i < n; i++) {\n        printf(\"%d%c\", nums[i], (i == n - 1) ? '\\n' : ' ');\n    }\n    return 0;\n}",
    "python_class": "class Solution:\n    def rotate(self, nums: List[int], k: int) -> None:\n        n = len(nums)\n        if n == 0: return\n        k = k % n\n        if k > 0:\n            nums[:] = nums[-k:] + nums[:-k]\n",
  },
  "valid_parentheses": {
    "python": "s = input().strip()\nstack = []\nmapping = {')': '(', '}': '{', ']': '['}\nvalid = True\nfor ch in s:\n    if ch in mapping.values():\n        stack.append(ch)\n    elif ch in mapping:\n        if not stack or stack.pop() != mapping[ch]:\n            valid = False\n            break\n    else:\n        valid = False\n        break\nprint(\"true\" if valid and not stack else \"false\")\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public boolean isValid(String s) {\n        Stack<Character> st = new Stack<>();\n        for (char c : s.toCharArray()) {\n            if (c == '(') st.push(')');\n            else if (c == '{') st.push('}');\n            else if (c == '[') st.push(']');\n            else if (st.isEmpty() || st.pop() != c) return false;\n        }\n        return st.isEmpty();\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100005];\n    if (scanf(\"%s\", s) != 1) {\n        printf(\"true\\n\");\n        return 0;\n    }\n    char stack[100005];\n    int top = -1;\n    for (int i = 0; s[i]; i++) {\n        char c = s[i];\n        if (c == '(' || c == '{' || c == '[') {\n            stack[++top] = c;\n        } else {\n            if (top == -1) { printf(\"false\\n\"); return 0; }\n            char open = stack[top--];\n            if ((c == ')' && open != '(') ||\n                (c == '}' && open != '{') ||\n                (c == ']' && open != '[')) {\n                printf(\"false\\n\");\n                return 0;\n            }\n        }\n    }\n    if (top == -1) printf(\"true\\n\");\n    else printf(\"false\\n\");\n    return 0;\n}",
    "python_class": "class Solution:\n    def isValid(self, s: str) -> bool:\n        stack = []\n        mapping = {')': '(', '}': '{', ']': '['}\n        for ch in s:\n            if ch in mapping.values():\n                stack.append(ch)\n            elif ch in mapping:\n                if not stack or stack.pop() != mapping[ch]:\n                    return False\n            else:\n                return False\n        return len(stack) == 0\n",
  },
  "binary_tree": {
    "python": "import sys\nfrom collections import deque\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    nodes = [int(x) for x in data[1:n+1]]\n    if not nodes or nodes[0] == -1:\n        pass\n    else:\n        q = deque([0])\n        while q:\n            sz = len(q)\n            level = []\n            for _ in range(sz):\n                curr = q.popleft()\n                level.append(str(nodes[curr]))\n                left = 2 * curr + 1\n                right = 2 * curr + 2\n                if left < n and nodes[left] != -1:\n                    q.append(left)\n                if right < n and nodes[right] != -1:\n                    q.append(right)\n            print(\" \".join(level))\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public List<List<Integer>> levelOrder(int[] tree) {\n        List<List<Integer>> res = new ArrayList<>();\n        if (tree == null || tree.length == 0 || tree[0] == -1) return res;\n        Queue<Integer> q = new LinkedList<>();\n        q.offer(0);\n        int n = tree.length;\n        while (!q.isEmpty()) {\n            int sz = q.size();\n            List<Integer> level = new ArrayList<>();\n            for (int i = 0; i < sz; i++) {\n                int curr = q.poll();\n                level.add(tree[curr]);\n                int left = 2 * curr + 1;\n                int right = 2 * curr + 2;\n                if (left < n && tree[left] != -1) q.offer(left);\n                if (right < n && tree[right] != -1) q.offer(right);\n            }\n            res.add(level);\n        }\n        return res;\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int tree[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &tree[i]);\n    if (n == 0 || tree[0] == -1) return 0;\n\n    int q[100005];\n    int head = 0, tail = 0;\n    q[tail++] = 0;\n\n    while (head < tail) {\n        int sz = tail - head;\n        for (int i = 0; i < sz; i++) {\n            int curr = q[head++];\n            printf(\"%d%c\", tree[curr], (i == sz - 1) ? '\\n' : ' ');\n            int left = 2 * curr + 1, right = 2 * curr + 2;\n            if (left < n && tree[left] != -1) q[tail++] = left;\n            if (right < n && tree[right] != -1) q[tail++] = right;\n        }\n    }\n    return 0;\n}",
    "python_class": "from collections import deque\n\nclass Solution:\n    def levelOrder(self, nodes: List[int]) -> List[List[int]]:\n        if not nodes or nodes[0] == -1:\n            return []\n        n = len(nodes)\n        q = deque([0])\n        res = []\n        while q:\n            sz = len(q)\n            level = []\n            for _ in range(sz):\n                curr = q.popleft()\n                level.append(nodes[curr])\n                left = 2 * curr + 1\n                right = 2 * curr + 2\n                if left < n and nodes[left] != -1:\n                    q.append(left)\n                if right < n and nodes[right] != -1:\n                    q.append(right)\n            res.append(level)\n        return res\n",
  },
  "dijkstra_algorithm": {
    "python": "import sys\nimport heapq\n\ndata = sys.stdin.read().split()\nif data:\n    v = int(data[0])\n    e = int(data[1])\n    src = int(data[2])\n    adj = {i: [] for i in range(v)}\n    idx = 3\n    for _ in range(e):\n        u, w_node, w = int(data[idx]), int(data[idx+1]), int(data[idx+2])\n        adj[u].append((w_node, w))\n        idx += 3\n    \n    dist = [float('inf')] * v\n    dist[src] = 0\n    pq = [(0, src)]\n    while pq:\n        d, u = heapq.heappop(pq)\n        if d > dist[u]:\n            continue\n        for v_node, w in adj[u]:\n            if dist[u] + w < dist[v_node]:\n                dist[v_node] = dist[u] + w\n                heapq.heappush(pq, (dist[v_node], v_node))\n    \n    res = [str(x if x != float('inf') else -1) for x in dist]\n    print(' '.join(res))\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int[] dijkstra(int n, int[][] edges, int start) {\n        List<List<int[]>> adj = new ArrayList<>();\n        for (int i = 0; i < n; i++) adj.add(new ArrayList<>());\n        for (int[] e : edges) {\n            adj.get(e[0]).add(new int[]{e[1], e[2]});\n        }\n        int[] dist = new int[n];\n        Arrays.fill(dist, Integer.MAX_VALUE);\n        dist[start] = 0;\n        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> Integer.compare(a[1], b[1]));\n        pq.offer(new int[]{start, 0});\n        while (!pq.isEmpty()) {\n            int[] cur = pq.poll();\n            int u = cur[0], d = cur[1];\n            if (d > dist[u]) continue;\n            for (int[] edge : adj.get(u)) {\n                int v = edge[0], w = edge[1];\n                if (dist[u] + w < dist[v]) {\n                    dist[v] = dist[u] + w;\n                    pq.offer(new int[]{v, dist[v]});\n                }\n            }\n        }\n        for (int i = 0; i < n; i++) if (dist[i] == Integer.MAX_VALUE) dist[i] = -1;\n        return dist;\n    }\n}",
    "c": "#include <stdio.h>\n#include <limits.h>\n\nint main() {\n    int v, e, src;\n    if (scanf(\"%d %d %d\", &v, &e, &src) != 3) return 0;\n    int cost[v][v];\n    for (int i = 0; i < v; i++) {\n        for (int j = 0; j < v; j++) cost[i][j] = (i == j) ? 0 : 100000000;\n    }\n    for (int i = 0; i < e; i++) {\n        int u, to, w;\n        scanf(\"%d %d %d\", &u, &to, &w);\n        cost[u][to] = w;\n    }\n    int dist[v], visited[v];\n    for (int i = 0; i < v; i++) { dist[i] = 100000000; visited[i] = 0; }\n    dist[src] = 0;\n\n    for (int count = 0; count < v - 1; count++) {\n        int min_d = 100000000, u = -1;\n        for (int i = 0; i < v; i++) {\n            if (!visited[i] && dist[i] < min_d) { min_d = dist[i]; u = i; }\n        }\n        if (u == -1) break;\n        visited[u] = 1;\n        for (int j = 0; j < v; j++) {\n            if (!visited[j] && cost[u][j] < 100000000 && dist[u] + cost[u][j] < dist[j]) {\n                dist[j] = dist[u] + cost[u][j];\n            }\n        }\n    }\n    for (int i = 0; i < v; i++) {\n        int d = (dist[i] >= 100000000) ? -1 : dist[i];\n        printf(\"%d%c\", d, (i == v - 1) ? '\\n' : ' ');\n    }\n    return 0;\n}",
    "python_class": "import heapq\n\nclass Solution:\n    def dijkstra(self, v: int, edges: List[List[int]], src: int) -> List[int]:\n        adj = {i: [] for i in range(v)}\n        for edge in edges:\n            u, w_node, w = edge[0], edge[1], edge[2]\n            adj[u].append((w_node, w))\n        dist = [float('inf')] * v\n        dist[src] = 0\n        pq = [(0, src)]\n        while pq:\n            d, u = heapq.heappop(pq)\n            if d > dist[u]:\n                continue\n            for v_node, w in adj[u]:\n                if dist[u] + w < dist[v_node]:\n                    dist[v_node] = dist[u] + w\n                    heapq.heappush(pq, (dist[v_node], v_node))\n        return [x if x != float('inf') else -1 for x in dist]\n",
  },
  "n_queens": {
    "python": "import sys\ns = sys.stdin.read().strip()\nif s:\n    n = int(s)\n    cols = set()\n    diag1 = set()\n    diag2 = set()\n    ans = [0]\n    def backtrack(r):\n        if r == n:\n            ans[0] += 1\n            return\n        for c in range(n):\n            if c in cols or (r - c) in diag1 or (r + c) in diag2:\n                continue\n            cols.add(c)\n            diag1.add(r - c)\n            diag2.add(r + c)\n            backtrack(r + 1)\n            cols.remove(c)\n            diag1.remove(r - c)\n            diag2.remove(r + c)\n    backtrack(0)\n    print(ans[0])\n",
    "java": "import java.util.*;\n\nclass Solution {\n    private int count = 0;\n    public int totalNQueens(int n) {\n        count = 0;\n        solve(0, n, new HashSet<>(), new HashSet<>(), new HashSet<>());\n        return count;\n    }\n    private void solve(int row, int n, Set<Integer> cols, Set<Integer> d1, Set<Integer> d2) {\n        if (row == n) { count++; return; }\n        for (int col = 0; col < n; col++) {\n            if (cols.contains(col) || d1.contains(row - col) || d2.contains(row + col)) continue;\n            cols.add(col); d1.add(row - col); d2.add(row + col);\n            solve(row + 1, n, cols, d1, d2);\n            cols.remove(col); d1.remove(row - col); d2.remove(row + col);\n        }\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint total_count = 0;\n\nvoid solve(int row, int n, int cols, int d1, int d2) {\n    if (row == n) { total_count++; return; }\n    int available = ((1 << n) - 1) & ~(cols | d1 | d2);\n    while (available) {\n        int bit = available & -available;\n        available -= bit;\n        solve(row + 1, n, cols | bit, (d1 | bit) << 1, (d2 | bit) >> 1);\n    }\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    total_count = 0;\n    solve(0, n, 0, 0, 0);\n    printf(\"%d\\n\", total_count);\n    return 0;\n}",
    "python_class": "class Solution:\n    def totalNQueens(self, n: int) -> int:\n        cols = set()\n        diag1 = set()\n        diag2 = set()\n        count = 0\n        def backtrack(r):\n            nonlocal count\n            if r == n:\n                count += 1\n                return\n            for c in range(n):\n                if c in cols or (r - c) in diag1 or (r + c) in diag2:\n                    continue\n                cols.add(c)\n                diag1.add(r - c)\n                diag2.add(r + c)\n                backtrack(r + 1)\n                cols.remove(c)\n                diag1.remove(r - c)\n                diag2.remove(r + c)\n        backtrack(0)\n        return count\n",
  },
  "shortest_path": {
    "python": "import sys\nfrom collections import deque\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    e = int(data[1])\n    start = int(data[2])\n    end = int(data[3])\n    adj = {i: [] for i in range(n)}\n    idx = 4\n    for _ in range(e):\n        u, v = int(data[idx]), int(data[idx+1])\n        adj[u].append(v)\n        adj[v].append(u)\n        idx += 2\n    \n    dist = {start: 0}\n    queue = deque([start])\n    while queue:\n        u = queue.popleft()\n        if u == end:\n            break\n        for v in adj[u]:\n            if v not in dist:\n                dist[v] = dist[u] + 1\n                queue.append(v)\n    print(dist.get(end, -1))\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int shortestPath(int n, int[][] edges, int start, int end) {\n        List<List<Integer>> adj = new ArrayList<>();\n        for (int i = 0; i < n; i++) adj.add(new ArrayList<>());\n        for (int[] e : edges) {\n            adj.get(e[0]).add(e[1]);\n            adj.get(e[1]).add(e[0]);\n        }\n        Queue<int[]> q = new LinkedList<>();\n        boolean[] visited = new boolean[n];\n        q.offer(new int[]{start, 0});\n        visited[start] = true;\n        while (!q.isEmpty()) {\n            int[] cur = q.poll();\n            int u = cur[0], d = cur[1];\n            if (u == end) return d;\n            for (int v : adj.get(u)) {\n                if (!visited[v]) {\n                    visited[v] = true;\n                    q.offer(new int[]{v, d + 1});\n                }\n            }\n        }\n        return -1;\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int v, e, start, end;\n    if (scanf(\"%d %d %d %d\", &v, &e, &start, &end) != 4) return 0;\n    if (start == end) {\n        printf(\"0\\n\");\n        return 0;\n    }\n    int adj[v][v];\n    for (int i = 0; i < v; i++) {\n        for (int j = 0; j < v; j++) adj[i][j] = 0;\n    }\n    for (int i = 0; i < e; i++) {\n        int u, to;\n        scanf(\"%d %d\", &u, &to);\n        if (u >= 0 && u < v && to >= 0 && to < v) {\n            adj[u][to] = adj[to][u] = 1;\n        }\n    }\n\n    int q[10005], dist[10005], visited[10005];\n    for (int i = 0; i < v; i++) visited[i] = 0;\n    int head = 0, tail = 0;\n\n    q[tail] = start; dist[tail] = 0; tail++;\n    visited[start] = 1;\n\n    int ans = -1;\n    while (head < tail) {\n        int u = q[head], d = dist[head++];\n        if (u == end) { ans = d; break; }\n        for (int to = 0; to < v; to++) {\n            if (adj[u][to] && !visited[to]) {\n                visited[to] = 1;\n                q[tail] = to; dist[tail] = d + 1; tail++;\n            }\n        }\n    }\n    printf(\"%d\\n\", ans);\n    return 0;\n}",
    "python_class": "from collections import deque\n\nclass Solution:\n    def shortestPath(self, v: int, edges: List[List[int]], start: int, end: int) -> int:\n        adj = {i: [] for i in range(v)}\n        for edge in edges:\n            u, to_node = edge[0], edge[1]\n            adj[u].append(to_node)\n            adj[to_node].append(u)\n        dist = {start: 0}\n        queue = deque([start])\n        while queue:\n            u = queue.popleft()\n            if u == end:\n                break\n            for neighbor in adj[u]:\n                if neighbor not in dist:\n                    dist[neighbor] = dist[u] + 1\n                    queue.append(neighbor)\n        return dist.get(end, -1)\n",
  },
  "word_ladder": {
    "python": "import sys\nfrom collections import deque\ndata = sys.stdin.read().split()\nif data:\n    begin_word = data[0]\n    end_word = data[1]\n    n = int(data[2])\n    word_set = set(data[3:3+n])\n    if end_word not in word_set:\n        print(0)\n    else:\n        queue = deque([(begin_word, 1)])\n        visited = {begin_word}\n        found = False\n        while queue:\n            word, length = queue.popleft()\n            if word == end_word:\n                print(length)\n                found = True\n                break\n            for i in range(len(word)):\n                for c in 'abcdefghijklmnopqrstuvwxyz':\n                    next_word = word[:i] + c + word[i+1:]\n                    if next_word in word_set and next_word not in visited:\n                        visited.add(next_word)\n                        queue.append((next_word, length + 1))\n        if not found:\n            print(0)\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int ladderLength(String beginWord, String endWord, List<String> wordList) {\n        Set<String> words = new HashSet<>(wordList);\n        if (!words.contains(endWord)) return 0;\n        Queue<String> q = new LinkedList<>();\n        Set<String> visited = new HashSet<>();\n        q.offer(beginWord);\n        visited.add(beginWord);\n        int step = 1;\n        while (!q.isEmpty()) {\n            int sz = q.size();\n            for (int s = 0; s < sz; s++) {\n                String word = q.poll();\n                if (word.equals(endWord)) return step;\n                char[] chars = word.toCharArray();\n                for (int i = 0; i < chars.length; i++) {\n                    char orig = chars[i];\n                    for (char c = 'a'; c <= 'z'; c++) {\n                        chars[i] = c;\n                        String nw = new String(chars);\n                        if (words.contains(nw) && !visited.contains(nw)) {\n                            visited.add(nw);\n                            q.offer(nw);\n                        }\n                    }\n                    chars[i] = orig;\n                }\n            }\n            step++;\n        }\n        return 0;\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n#include <stdlib.h>\n\nint diff_one(const char* a, const char* b) {\n    int diff = 0;\n    for (int i = 0; a[i] && b[i]; i++) {\n        if (a[i] != b[i]) { diff++; if (diff > 1) return 0; }\n    }\n    return diff == 1;\n}\n\nint main() {\n    char beginWord[105], endWord[105];\n    if (scanf(\"%s %s\", beginWord, endWord) != 2) return 0;\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    char words[n][105];\n    int end_idx = -1;\n    for (int i = 0; i < n; i++) {\n        scanf(\"%s\", words[i]);\n        if (strcmp(words[i], endWord) == 0) end_idx = i;\n    }\n    if (end_idx == -1) { printf(\"0\\n\"); return 0; }\n\n    int q[1005], dist[1005], visited[1005];\n    memset(visited, 0, sizeof(visited));\n    int head = 0, tail = 0;\n\n    for (int i = 0; i < n; i++) {\n        if (diff_one(beginWord, words[i])) {\n            q[tail] = i; dist[tail] = 2; visited[i] = 1; tail++;\n        }\n    }\n\n    int ans = 0;\n    while (head < tail) {\n        int u = q[head], d = dist[head++];\n        if (u == end_idx) { ans = d; break; }\n        for (int v = 0; v < n; v++) {\n            if (!visited[v] && diff_one(words[u], words[v])) {\n                visited[v] = 1;\n                q[tail] = v; dist[tail] = d + 1; tail++;\n            }\n        }\n    }\n    printf(\"%d\\n\", ans);\n    return 0;\n}",
    "python_class": "from collections import deque\n\nclass Solution:\n    def ladderLength(self, beginWord: str, endWord: str, wordList: List[str]) -> int:\n        word_set = set(wordList)\n        if endWord not in word_set:\n            return 0\n        queue = deque([(beginWord, 1)])\n        visited = {beginWord}\n        while queue:\n            word, length = queue.popleft()\n            if word == endWord:\n                return length\n            for i in range(len(word)):\n                for c in 'abcdefghijklmnopqrstuvwxyz':\n                    next_word = word[:i] + c + word[i+1:]\n                    if next_word in word_set and next_word not in visited:\n                        visited.add(next_word)\n                        queue.append((next_word, length + 1))\n        return 0\n",
  },
  "climbing_stairs": {
    "python": "n = int(input())\nif n <= 2:\n    print(n)\nelse:\n    a, b = 1, 2\n    for _ in range(3, n + 1):\n        a, b = b, a + b\n    print(b)\n",
    "java": "class Solution {\n    public int climbStairs(int n) {\n        if (n <= 2) return n;\n        int a = 1, b = 2;\n        for (int i = 3; i <= n; i++) {\n            int c = a + b;\n            a = b;\n            b = c;\n        }\n        return b;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    if (n <= 2) { printf(\"%d\\n\", n); return 0; }\n    int a = 1, b = 2;\n    for (int i = 3; i <= n; i++) {\n        int c = a + b;\n        a = b;\n        b = c;\n    }\n    printf(\"%d\\n\", b);\n    return 0;\n}",
    "python_class": "class Solution:\n    def climbStairs(self, n: int) -> int:\n        if n <= 2:\n            return n\n        a, b = 1, 2\n        for _ in range(3, n + 1):\n            a, b = b, a + b\n        return b\n",
  },
  "majority_element": {
    "python": "n = int(input())\nnums = list(map(int, input().split()))\ncand = None\ncount = 0\nfor num in nums:\n    if count == 0:\n        cand = num\n    count += (1 if num == cand else -1)\nprint(cand)\n",
    "java": "class Solution {\n    public int majorityElement(int[] nums) {\n        int cand = nums[0], count = 0;\n        for (int x : nums) {\n            if (count == 0) cand = x;\n            count += (x == cand ? 1 : -1);\n        }\n        return cand;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int cand = nums[0], count = 0;\n    for (int i = 0; i < n; i++) {\n        if (count == 0) cand = nums[i];\n        count += (nums[i] == cand ? 1 : -1);\n    }\n    printf(\"%d\\n\", cand);\n    return 0;\n}",
    "python_class": "class Solution:\n    def majorityElement(self, nums: List[int]) -> int:\n        cand = None\n        count = 0\n        for num in nums:\n            if count == 0:\n                cand = num\n            count += (1 if num == cand else -1)\n        return cand\n",
  },
  "reverse_words": {
    "python": "s = input().strip()\nwords = s.split()\nprint(' '.join(reversed(words)))\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public String reverseWords(String s) {\n        String[] parts = s.trim().split(\"\\\\s+\");\n        StringBuilder sb = new StringBuilder();\n        for (int i = parts.length - 1; i >= 0; i--) {\n            sb.append(parts[i]);\n            if (i > 0) sb.append(\" \");\n        }\n        return sb.toString();\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100005];\n    if (!fgets(s, sizeof(s), stdin)) return 0;\n    char words[1000][100];\n    int count = 0;\n    char* token = strtok(s, \" \\n\\r\\t\");\n    while (token) {\n        strcpy(words[count++], token);\n        token = strtok(NULL, \" \\n\\r\\t\");\n    }\n    for (int i = count - 1; i >= 0; i--) {\n        printf(\"%s%c\", words[i], (i == 0) ? '\\n' : ' ');\n    }\n    return 0;\n}",
    "python_class": "class Solution:\n    def reverseWords(self, s: str) -> str:\n        words = s.strip().split()\n        return ' '.join(reversed(words))\n",
  },
  "single_number": {
    "python": "n = int(input())\nnums = list(map(int, input().split()))\nres = 0\nfor x in nums:\n    res ^= x\nprint(res)\n",
    "java": "class Solution {\n    public int singleNumber(int[] nums) {\n        int res = 0;\n        for (int x : nums) res ^= x;\n        return res;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int ans = 0;\n    for (int i = 0; i < n; i++) {\n        int x; scanf(\"%d\", &x);\n        ans ^= x;\n    }\n    printf(\"%d\\n\", ans);\n    return 0;\n}",
    "python_class": "class Solution:\n    def singleNumber(self, nums: List[int]) -> int:\n        res = 0\n        for x in nums:\n            res ^= x\n        return res\n",
  },
  "coin_change": {
    "python": "n, amount = map(int, input().split())\ncoins = list(map(int, input().split()))\ndp = [float('inf')] * (amount + 1)\ndp[0] = 0\nfor coin in coins:\n    for i in range(coin, amount + 1):\n        dp[i] = min(dp[i], dp[i - coin] + 1)\nprint(dp[amount] if dp[amount] != float('inf') else -1)\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int coinChange(int[] coins, int amount) {\n        int[] dp = new int[amount + 1];\n        Arrays.fill(dp, amount + 1);\n        dp[0] = 0;\n        for (int c : coins) {\n            for (int x = c; x <= amount; x++) {\n                dp[x] = Math.min(dp[x], dp[x - c] + 1);\n            }\n        }\n        return dp[amount] > amount ? -1 : dp[amount];\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int n, amount;\n    if (scanf(\"%d %d\", &n, &amount) != 2) return 0;\n    int coins[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &coins[i]);\n\n    int dp[amount + 1];\n    for (int i = 0; i <= amount; i++) dp[i] = 100000000;\n    dp[0] = 0;\n\n    for (int i = 1; i <= amount; i++) {\n        for (int j = 0; j < n; j++) {\n            if (coins[j] <= i && dp[i - coins[j]] + 1 < dp[i]) {\n                dp[i] = dp[i - coins[j]] + 1;\n            }\n        }\n    }\n    printf(\"%d\\n\", (dp[amount] >= 100000000) ? -1 : dp[amount]);\n    return 0;\n}",
    "python_class": "class Solution:\n    def coinChange(self, coins: List[int], amount: int) -> int:\n        dp = [float('inf')] * (amount + 1)\n        dp[0] = 0\n        for coin in coins:\n            for i in range(coin, amount + 1):\n                dp[i] = min(dp[i], dp[i - coin] + 1)\n        return dp[amount] if dp[amount] != float('inf') else -1\n",
  },
  "container_with_most_water": {
    "python": "n = int(input())\nheight = list(map(int, input().split()))\nleft, right = 0, n - 1\nmax_area = 0\nwhile left < right:\n    area = min(height[left], height[right]) * (right - left)\n    max_area = max(max_area, area)\n    if height[left] < height[right]:\n        left += 1\n    else:\n        right -= 1\nprint(max_area)\n",
    "java": "class Solution {\n    public int maxArea(int[] height) {\n        int l = 0, r = height.length - 1, maxA = 0;\n        while (l < r) {\n            maxA = Math.max(maxA, Math.min(height[l], height[r]) * (r - l));\n            if (height[l] < height[r]) l++;\n            else r--;\n        }\n        return maxA;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int height[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &height[i]);\n\n    int l = 0, r = n - 1;\n    long max_area = 0;\n    while (l < r) {\n        int h = height[l] < height[r] ? height[l] : height[r];\n        long area = (long)h * (r - l);\n        if (area > max_area) max_area = area;\n        if (height[l] < height[r]) l++;\n        else r--;\n    }\n    printf(\"%ld\\n\", max_area);\n    return 0;\n}",
    "python_class": "class Solution:\n    def maxArea(self, height: List[int]) -> int:\n        left, right = 0, len(height) - 1\n        max_area = 0\n        while left < right:\n            area = min(height[left], height[right]) * (right - left)\n            max_area = max(max_area, area)\n            if height[left] < height[right]:\n                left += 1\n            else:\n                right -= 1\n        return max_area\n",
  },
  "group_anagrams": {
    "python": "n = int(input())\nwords = input().split()\ngroups = {}\nfor w in words:\n    key = ''.join(sorted(w))\n    groups.setdefault(key, []).append(w)\nprint(len(groups))\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int groupAnagrams(String[] strs) {\n        Map<String, List<String>> map = new HashMap<>();\n        for (String s : strs) {\n            char[] chars = s.toCharArray();\n            Arrays.sort(chars);\n            String key = new String(chars);\n            map.computeIfAbsent(key, k -> new ArrayList<>()).add(s);\n        }\n        return map.size();\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n#include <stdlib.h>\n\nint cmp_char(const void* a, const void* b) { return *(char*)a - *(char*)b; }\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    char words[n][105];\n    for (int i = 0; i < n; i++) scanf(\"%s\", words[i]);\n\n    char keys[n][105];\n    int num_groups = 0;\n\n    for (int i = 0; i < n; i++) {\n        char sorted[105];\n        strcpy(sorted, words[i]);\n        qsort(sorted, strlen(sorted), sizeof(char), cmp_char);\n\n        int found = 0;\n        for (int g = 0; g < num_groups; g++) {\n            if (strcmp(keys[g], sorted) == 0) {\n                found = 1;\n                break;\n            }\n        }\n        if (!found) {\n            strcpy(keys[num_groups++], sorted);\n        }\n    }\n\n    printf(\"%d\\n\", num_groups);\n    return 0;\n}",
    "python_class": "class Solution:\n    def groupAnagrams(self, strs: List[str]) -> int:\n        groups = {}\n        for w in strs:\n            key = ''.join(sorted(w))\n            groups.setdefault(key, []).append(w)\n        return len(groups)\n",
  },
  "rotate_matrix": {
    "python": "n = int(input())\nmatrix = []\nfor _ in range(n):\n    matrix.append(list(map(int, input().split())))\nfor i in range(n):\n    for j in range(i + 1, n):\n        matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\nfor row in matrix:\n    row.reverse()\n    print(' '.join(map(str, row)))\n",
    "java": "class Solution {\n    public void rotate(int[][] matrix) {\n        int n = matrix.length;\n        for (int i = 0; i < n; i++) {\n            for (int j = i + 1; j < n; j++) {\n                int t = matrix[i][j]; matrix[i][j] = matrix[j][i]; matrix[j][i] = t;\n            }\n        }\n        for (int i = 0; i < n; i++) {\n            int l = 0, r = n - 1;\n            while (l < r) {\n                int t = matrix[i][l]; matrix[i][l] = matrix[i][r]; matrix[i][r] = t;\n                l++; r--;\n            }\n        }\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int matrix[n][n];\n    for (int i = 0; i < n; i++) {\n        for (int j = 0; j < n; j++) scanf(\"%d\", &matrix[i][j]);\n    }\n\n    for (int i = 0; i < n; i++) {\n        for (int j = i + 1; j < n; j++) {\n            int t = matrix[i][j]; matrix[i][j] = matrix[j][i]; matrix[j][i] = t;\n        }\n    }\n    for (int i = 0; i < n; i++) {\n        for (int j = 0, k = n - 1; j < k; j++, k--) {\n            int t = matrix[i][j]; matrix[i][j] = matrix[i][k]; matrix[i][k] = t;\n        }\n    }\n    for (int i = 0; i < n; i++) {\n        for (int j = 0; j < n; j++) {\n            printf(\"%d%c\", matrix[i][j], (j == n - 1) ? '\\n' : ' ');\n        }\n    }\n    return 0;\n}",
    "python_class": "class Solution:\n    def rotate(self, matrix: List[List[int]]) -> None:\n        n = len(matrix)\n        for i in range(n):\n            for j in range(i + 1, n):\n                matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\n        for row in matrix:\n            row.reverse()\n",
  },
  "longest_valid_parentheses": {
    "python": "import sys\ns = sys.stdin.read().strip()\nif not s:\n    print(0)\nelse:\n    stack = [-1]\n    max_len = 0\n    for i, ch in enumerate(s):\n        if ch == '(':\n            stack.append(i)\n        else:\n            stack.pop()\n            if not stack:\n                stack.append(i)\n            else:\n                max_len = max(max_len, i - stack[-1])\n    print(max_len)\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int longestValidParentheses(String s) {\n        Stack<Integer> st = new Stack<>();\n        st.push(-1);\n        int maxLen = 0;\n        for (int i = 0; i < s.length(); i++) {\n            if (s.charAt(i) == '(') {\n                st.push(i);\n            } else {\n                st.pop();\n                if (st.isEmpty()) {\n                    st.push(i);\n                } else {\n                    maxLen = Math.max(maxLen, i - st.peek());\n                }\n            }\n        }\n        return maxLen;\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100005];\n    if (scanf(\"%s\", s) != 1) { printf(\"0\\n\"); return 0; }\n    int stack[100005];\n    int top = -1;\n    stack[++top] = -1;\n    int max_len = 0;\n\n    for (int i = 0; s[i]; i++) {\n        if (s[i] == '(') {\n            stack[++top] = i;\n        } else {\n            top--;\n            if (top == -1) {\n                stack[++top] = i;\n            } else {\n                int len = i - stack[top];\n                if (len > max_len) max_len = len;\n            }\n        }\n    }\n    printf(\"%d\\n\", max_len);\n    return 0;\n}",
    "python_class": "class Solution:\n    def longestValidParentheses(self, s: str) -> int:\n        stack = [-1]\n        max_len = 0\n        for i, ch in enumerate(s):\n            if ch == '(':\n                stack.append(i)\n            else:\n                stack.pop()\n                if not stack:\n                    stack.append(i)\n                else:\n                    max_len = max(max_len, i - stack[-1])\n        return max_len\n",
  },
  "median_two_sorted_arrays": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    m = int(data[1])\n    nums1 = [int(x) for x in data[2:2+n]]\n    nums2 = [int(x) for x in data[2+n:2+n+m]]\n    merged = sorted(nums1 + nums2)\n    total = n + m\n    if total % 2 == 1:\n        res = float(merged[total // 2])\n    else:\n        res = (merged[total // 2 - 1] + merged[total // 2]) / 2.0\n    print(f\"{res:.1f}\")\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public double findMedianSortedArrays(int[] nums1, int[] nums2) {\n        int[] merged = new int[nums1.length + nums2.length];\n        System.arraycopy(nums1, 0, merged, 0, nums1.length);\n        System.arraycopy(nums2, 0, merged, nums1.length, nums2.length);\n        Arrays.sort(merged);\n        int n = merged.length;\n        if (n % 2 == 1) return merged[n / 2];\n        return (merged[n / 2 - 1] + merged[n / 2]) / 2.0;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n, m;\n    if (scanf(\"%d %d\", &n, &m) != 2) return 0;\n    int a[n], b[m];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &a[i]);\n    for (int i = 0; i < m; i++) scanf(\"%d\", &b[i]);\n\n    int total = n + m;\n    if (total == 0) {\n        printf(\"0.0\\n\");\n        return 0;\n    }\n    int merged[total];\n    int i = 0, j = 0, k = 0;\n    while (i < n && j < m) merged[k++] = (a[i] < b[j]) ? a[i++] : b[j++];\n    while (i < n) merged[k++] = a[i++];\n    while (j < m) merged[k++] = b[j++];\n\n    if (total % 2 == 1) {\n        printf(\"%.1f\\n\", (double)merged[total / 2]);\n    } else {\n        printf(\"%.1f\\n\", (double)(merged[total / 2 - 1] + merged[total / 2]) / 2.0);\n    }\n    return 0;\n}",
    "python_class": "class Solution:\n    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:\n        merged = sorted(nums1 + nums2)\n        total = len(merged)\n        if total % 2 == 1:\n            return float(merged[total // 2])\n        else:\n            return (merged[total // 2 - 1] + merged[total // 2]) / 2.0\n",
  },
  "merge_k_sorted_lists": {
    "python": "import sys\nimport heapq\ndata = sys.stdin.read().split()\nif data:\n    k = int(data[0])\n    lists = []\n    idx = 1\n    for _ in range(k):\n        sz = int(data[idx])\n        lists.append([int(x) for x in data[idx+1:idx+1+sz]])\n        idx += 1 + sz\n    \n    pq = []\n    for i, l in enumerate(lists):\n        if l:\n            heapq.heappush(pq, (l[0], i, 0))\n    res = []\n    while pq:\n        val, list_idx, elem_idx = heapq.heappop(pq)\n        res.append(str(val))\n        if elem_idx + 1 < len(lists[list_idx]):\n            heapq.heappush(pq, (lists[list_idx][elem_idx + 1], list_idx, elem_idx + 1))\n    print(' '.join(res))\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int[] mergeKLists(int[][] lists) {\n        List<Integer> all = new ArrayList<>();\n        for (int[] lst : lists) {\n            for (int x : lst) all.add(x);\n        }\n        Collections.sort(all);\n        int[] res = new int[all.size()];\n        for (int i = 0; i < all.size(); i++) res[i] = all.get(i);\n        return res;\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint cmp(const void* a, const void* b) { return (*(int*)a - *(int*)b); }\n\nint main() {\n    int k;\n    if (scanf(\"%d\", &k) != 1 || k <= 0) return 0;\n    int all[100005];\n    int total = 0;\n    for (int i = 0; i < k; i++) {\n        int len; scanf(\"%d\", &len);\n        for (int j = 0; j < len; j++) scanf(\"%d\", &all[total++]);\n    }\n    qsort(all, total, sizeof(int), cmp);\n    for (int i = 0; i < total; i++) {\n        printf(\"%d%c\", all[i], (i == total - 1) ? '\\n' : ' ');\n    }\n    return 0;\n}",
    "python_class": "import heapq\n\nclass Solution:\n    def mergeKLists(self, lists: List[List[int]]) -> List[int]:\n        pq = []\n        for i, l in enumerate(lists):\n            if l:\n                heapq.heappush(pq, (l[0], i, 0))\n        res = []\n        while pq:\n            val, list_idx, elem_idx = heapq.heappop(pq)\n            res.append(val)\n            if elem_idx + 1 < len(lists[list_idx]):\n                heapq.heappush(pq, (lists[list_idx][elem_idx + 1], list_idx, elem_idx + 1))\n        return res\n",
  },
  "trapping_rain_water": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    height = [int(x) for x in data[1:n+1]]\n    if not height:\n        print(0)\n    else:\n        left, right = 0, n - 1\n        max_left, max_right = height[0], height[-1]\n        ans = 0\n        while left < right:\n            if max_left < max_right:\n                left += 1\n                max_left = max(max_left, height[left])\n                ans += max_left - height[left]\n            else:\n                right -= 1\n                max_right = max(max_right, height[right])\n                ans += max_right - height[right]\n        print(ans)\n",
    "java": "class Solution {\n    public int trap(int[] height) {\n        if (height == null || height.length == 0) return 0;\n        int l = 0, r = height.length - 1, lMax = 0, rMax = 0, water = 0;\n        while (l < r) {\n            if (height[l] < height[r]) {\n                if (height[l] >= lMax) lMax = height[l];\n                else water += lMax - height[l];\n                l++;\n            } else {\n                if (height[r] >= rMax) rMax = height[r];\n                else water += rMax - height[r];\n                r--;\n            }\n        }\n        return water;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1 || n <= 0) { printf(\"0\\n\"); return 0; }\n    int height[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &height[i]);\n\n    int l = 0, r = n - 1;\n    int left_max = 0, right_max = 0;\n    long total_water = 0;\n\n    while (l < r) {\n        if (height[l] < height[r]) {\n            if (height[l] >= left_max) left_max = height[l];\n            else total_water += left_max - height[l];\n            l++;\n        } else {\n            if (height[r] >= right_max) right_max = height[r];\n            else total_water += right_max - height[r];\n            r--;\n        }\n    }\n    printf(\"%ld\\n\", total_water);\n    return 0;\n}",
    "python_class": "class Solution:\n    def trap(self, height: List[int]) -> int:\n        if not height:\n            return 0\n        left, right = 0, len(height) - 1\n        max_left, max_right = height[0], height[-1]\n        ans = 0\n        while left < right:\n            if max_left < max_right:\n                left += 1\n                max_left = max(max_left, height[left])\n                ans += max_left - height[left]\n            else:\n                right -= 1\n                max_right = max(max_right, height[right])\n                ans += max_right - height[right]\n        return ans\n",
  },
  "word_break": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    s = data[0]\n    n = int(data[1])\n    word_set = set(data[2:2+n])\n    dp = [False] * (len(s) + 1)\n    dp[0] = True\n    for i in range(1, len(s) + 1):\n        for j in range(i):\n            if dp[j] and s[j:i] in word_set:\n                dp[i] = True\n                break\n    print(\"true\" if dp[len(s)] else \"false\")\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public boolean wordBreak(String s, List<String> wordDict) {\n        Set<String> words = new HashSet<>(wordDict);\n        int n = s.length();\n        boolean[] dp = new boolean[n + 1];\n        dp[0] = true;\n        for (int i = 1; i <= n; i++) {\n            for (int j = 0; j < i; j++) {\n                if (dp[j] && words.contains(s.substring(j, i))) {\n                    dp[i] = true;\n                    break;\n                }\n            }\n        }\n        return dp[n];\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n#include <stdbool.h>\n\nint main() {\n    char s[100005];\n    if (scanf(\"%s\", s) != 1) { printf(\"false\\n\"); return 0; }\n    int n;\n    if (scanf(\"%d\", &n) != 1) { printf(\"false\\n\"); return 0; }\n    char dict[n][105];\n    for (int i = 0; i < n; i++) scanf(\"%s\", dict[i]);\n\n    int len = strlen(s);\n    bool dp[len + 1];\n    memset(dp, 0, sizeof(dp));\n    dp[0] = true;\n\n    for (int i = 1; i <= len; i++) {\n        for (int j = 0; j < i; j++) {\n            if (dp[j]) {\n                char sub[105];\n                int sub_len = i - j;\n                if (sub_len >= 100) continue;\n                strncpy(sub, s + j, sub_len);\n                sub[sub_len] = '\\0';\n                for (int d = 0; d < n; d++) {\n                    if (strcmp(sub, dict[d]) == 0) {\n                        dp[i] = true;\n                        break;\n                    }\n                }\n                if (dp[i]) break;\n            }\n        }\n    }\n    printf(\"%s\\n\", dp[len] ? \"true\" : \"false\");\n    return 0;\n}",
    "python_class": "class Solution:\n    def wordBreak(self, s: str, wordDict: List[str]) -> bool:\n        word_set = set(wordDict)\n        dp = [False] * (len(s) + 1)\n        dp[0] = True\n        for i in range(1, len(s) + 1):\n            for j in range(i):\n                if dp[j] and s[j:i] in word_set:\n                    dp[i] = True\n                    break\n        return dp[len(s)]\n",
  },
}
