"""
CODE COMBAT Pro - Solutions Registry
"""

from typing import Dict, Any, Optional

SOLUTIONS_REGISTRY: Dict[str, Dict[str, str]] = {
  "two_sum": {
    "python": "import sys\n\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    nums = [int(x) for x in data[1:n+1]]\n    target = int(data[n+1])\n    m = {}\n    for i, num in enumerate(nums):\n        diff = target - num\n        if diff in m:\n            print(f\"{m[diff]} {i}\")\n            break\n        m[num] = i\n",
    "python_class": "class Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n        m = {}\n        for i, n in enumerate(nums):\n            comp = target - n\n            if comp in m:\n                return [m[comp], i]\n            m[n] = i\n        return []\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int[] twoSum(int[] nums, int target) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int comp = target - nums[i];\n            if (map.containsKey(comp)) {\n                return new int[]{map.get(comp), i};\n            }\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int target;\n    scanf(\"%d\", &target);\n    for (int i = 0; i < n; i++) {\n        for (int j = i + 1; j < n; j++) {\n            if (nums[i] + nums[j] == target) {\n                printf(\"%d %d\\n\", i, j);\n                return 0;\n            }\n        }\n    }\n    return 0;\n}"
  },
  "reverse_string": {
    "python": "import sys\n\ns = sys.stdin.read().rstrip('\\r\\n')\nprint(s[::-1])\n",
    "python_class": "class Solution:\n    def reverseString(self, s: str) -> str:\n        return s[::-1]\n",
    "java": "class Solution {\n    public String reverseString(String s) {\n        return new StringBuilder(s).reverse().toString();\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100005];\n    if (!fgets(s, sizeof(s), stdin)) return 0;\n    int len = strlen(s);\n    while (len > 0 && (s[len - 1] == '\\n' || s[len - 1] == '\\r')) {\n        s[--len] = '\\0';\n    }\n    for (int i = 0, j = len - 1; i < j; i++, j--) {\n        char t = s[i]; s[i] = s[j]; s[j] = t;\n    }\n    printf(\"%s\\n\", s);\n    return 0;\n}"
  },
  "find_duplicate": {
    "python": "import sys\n\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    nums = [int(x) for x in data[1:n+1]]\n    seen = set()\n    for x in nums:\n        if x in seen:\n            print(x)\n            break\n        seen.add(x)\n",
    "python_class": "class Solution:\n    def findDuplicate(self, nums: List[int]) -> int:\n        seen = set()\n        for x in nums:\n            if x in seen:\n                return x\n            seen.add(x)\n        return 0\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int findDuplicate(int[] nums) {\n        Set<Integer> seen = new HashSet<>();\n        for (int x : nums) {\n            if (seen.contains(x)) return x;\n            seen.add(x);\n        }\n        return 0;\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    for (int i = 0; i < n; i++) {\n        for (int j = i + 1; j < n; j++) {\n            if (nums[i] == nums[j]) {\n                printf(\"%d\\n\", nums[i]);\n                return 0;\n            }\n        }\n    }\n    return 0;\n}"
  },
  "valid_parentheses": {
    "python": "import sys\n\ns = sys.stdin.read().strip()\npairs = {')': '(', '}': '{', ']': '['}\nstack = []\nok = True\nfor ch in s:\n    if ch in pairs.values():\n        stack.append(ch)\n    elif ch in pairs:\n        if not stack or stack.pop() != pairs[ch]:\n            ok = False\n            break\nprint(\"true\" if ok and not stack else \"false\")\n",
    "python_class": "class Solution:\n    def isValid(self, s: str) -> bool:\n        pairs = {')': '(', '}': '{', ']': '['}\n        stack = []\n        for ch in s:\n            if ch in pairs.values():\n                stack.append(ch)\n            elif ch in pairs:\n                if not stack or stack.pop() != pairs[ch]:\n                    return False\n        return not stack\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public boolean isValid(String s) {\n        Stack<Character> st = new Stack<>();\n        for (char c : s.toCharArray()) {\n            if (c == '(') st.push(')');\n            else if (c == '{') st.push('}');\n            else if (c == '[') st.push(']');\n            else if (st.isEmpty() || st.pop() != c) return false;\n        }\n        return st.isEmpty();\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdbool.h>\n#include <string.h>\n\nint main() {\n    char s[100005];\n    if (scanf(\"%s\", s) != 1) { printf(\"false\\n\"); return 0; }\n    char st[100005];\n    int top = -1;\n    for (int i = 0; s[i]; i++) {\n        if (s[i] == '(') st[++top] = ')';\n        else if (s[i] == '{') st[++top] = '}';\n        else if (s[i] == '[') st[++top] = ']';\n        else {\n            if (top == -1 || st[top--] != s[i]) {\n                printf(\"false\\n\");\n                return 0;\n            }\n        }\n    }\n    printf(\"%s\\n\", top == -1 ? \"true\" : \"false\");\n    return 0;\n}"
  },
  "reverse_linked_list": {
    "python": "import sys\n\ndata = sys.stdin.read().split()\nif not data or int(data[0]) <= 0:\n    pass\nelse:\n    n = int(data[0])\n    nums = [data[i] for i in range(1, n + 1)]\n    print(' '.join(reversed(nums)))\n",
    "python_class": "class Solution:\n    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:\n        prev = None\n        curr = head\n        while curr:\n            nxt = curr.next\n            curr.next = prev\n            prev = curr\n            curr = nxt\n        return prev\n",
    "java": "class Solution {\n    public ListNode reverseList(ListNode head) {\n        ListNode prev = null, curr = head;\n        while (curr != null) {\n            ListNode nxt = curr.next;\n            curr.next = prev;\n            prev = curr;\n            curr = nxt;\n        }\n        return prev;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1 || n <= 0) return 0;\n    int arr[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &arr[i]);\n    for (int i = n - 1; i >= 0; i--) {\n        printf(\"%d%c\", arr[i], (i == 0) ? '\\n' : ' ');\n    }\n    return 0;\n}"
  },
  "longest_substring": {
    "python": "import sys\n\ns = sys.stdin.read().rstrip('\\r\\n')\nseen = {}\nleft = 0\nmax_len = 0\nfor right, ch in enumerate(s):\n    if ch in seen and seen[ch] >= left:\n        left = seen[ch] + 1\n    seen[ch] = right\n    max_len = max(max_len, right - left + 1)\nprint(max_len)\n",
    "python_class": "class Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:\n        seen = {}\n        left = 0\n        max_len = 0\n        for right, ch in enumerate(s):\n            if ch in seen and seen[ch] >= left:\n                left = seen[ch] + 1\n            seen[ch] = right\n            max_len = max(max_len, right - left + 1)\n        return max_len\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int lengthOfLongestSubstring(String s) {\n        Map<Character, Integer> map = new HashMap<>();\n        int left = 0, maxLen = 0;\n        for (int right = 0; right < s.length(); right++) {\n            char c = s.charAt(right);\n            if (map.containsKey(c) && map.get(c) >= left) {\n                left = map.get(c) + 1;\n            }\n            map.put(c, right);\n            maxLen = Math.max(maxLen, right - left + 1);\n        }\n        return maxLen;\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100005];\n    if (!fgets(s, sizeof(s), stdin)) {\n        printf(\"0\\n\");\n        return 0;\n    }\n    int len = strlen(s);\n    while (len > 0 && (s[len - 1] == '\\n' || s[len - 1] == '\\r')) {\n        s[--len] = '\\0';\n    }\n    int last[256];\n    for (int i = 0; i < 256; i++) last[i] = -1;\n    int max_len = 0, start = 0;\n    for (int i = 0; i < len; i++) {\n        unsigned char c = (unsigned char)s[i];\n        if (last[c] >= start) start = last[c] + 1;\n        last[c] = i;\n        int cur = i - start + 1;\n        if (cur > max_len) max_len = cur;\n    }\n    printf(\"%d\\n\", max_len);\n    return 0;\n}"
  },
  "three_sum": {
    "python": "import sys\n\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    nums = sorted([int(x) for x in data[1:n+1]])\n    for i in range(n - 2):\n        if i > 0 and nums[i] == nums[i - 1]:\n            continue\n        l, r = i + 1, n - 1\n        while l < r:\n            s = nums[i] + nums[l] + nums[r]\n            if s == 0:\n                print(f\"{nums[i]} {nums[l]} {nums[r]}\")\n                while l < r and nums[l] == nums[l + 1]: l += 1\n                while l < r and nums[r] == nums[r - 1]: r -= 1\n                l += 1; r -= 1\n            elif s < 0:\n                l += 1\n            else:\n                r -= 1\n",
    "python_class": "class Solution:\n    def threeSum(self, nums: List[int]) -> List[List[int]]:\n        nums.sort()\n        res = []\n        n = len(nums)\n        for i in range(n - 2):\n            if i > 0 and nums[i] == nums[i - 1]:\n                continue\n            l, r = i + 1, n - 1\n            while l < r:\n                s = nums[i] + nums[l] + nums[r]\n                if s == 0:\n                    res.append([nums[i], nums[l], nums[r]])\n                    while l < r and nums[l] == nums[l + 1]: l += 1\n                    while l < r and nums[r] == nums[r - 1]: r -= 1\n                    l += 1; r -= 1\n                elif s < 0:\n                    l += 1\n                else:\n                    r -= 1\n        return res\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public List<List<Integer>> threeSum(int[] nums) {\n        Arrays.sort(nums);\n        List<List<Integer>> res = new ArrayList<>();\n        int n = nums.length;\n        for (int i = 0; i < n - 2; i++) {\n            if (i > 0 && nums[i] == nums[i - 1]) continue;\n            int l = i + 1, r = n - 1;\n            while (l < r) {\n                int s = nums[i] + nums[l] + nums[r];\n                if (s == 0) {\n                    res.add(Arrays.asList(nums[i], nums[l], nums[r]));\n                    while (l < r && nums[l] == nums[l + 1]) l++;\n                    while (l < r && nums[r] == nums[r - 1]) r--;\n                    l++; r--;\n                } else if (s < 0) {\n                    l++;\n                } else {\n                    r--;\n                }\n            }\n        }\n        return res;\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint cmp(const void* a, const void* b) { return (*(int*)a - *(int*)b); }\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1 || n < 3) return 0;\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    qsort(nums, n, sizeof(int), cmp);\n\n    for (int i = 0; i < n - 2; i++) {\n        if (i > 0 && nums[i] == nums[i - 1]) continue;\n        int l = i + 1, r = n - 1;\n        while (l < r) {\n            int s = nums[i] + nums[l] + nums[r];\n            if (s == 0) {\n                printf(\"%d %d %d\\n\", nums[i], nums[l], nums[r]);\n                while (l < r && nums[l] == nums[l + 1]) l++;\n                while (l < r && nums[r] == nums[r - 1]) r--;\n                l++; r--;\n            } else if (s < 0) {\n                l++;\n            } else {\n                r--;\n            }\n        }\n    }\n    return 0;\n}"
  },
  "merge_intervals": {
    "python": "import sys\n\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    intervals = []\n    idx = 1\n    for _ in range(n):\n        intervals.append([int(data[idx]), int(data[idx+1])])\n        idx += 2\n    intervals.sort(key=lambda x: x[0])\n    merged = [intervals[0]]\n    for cur in intervals[1:]:\n        if cur[0] <= merged[-1][1]:\n            merged[-1][1] = max(merged[-1][1], cur[1])\n        else:\n            merged.append(cur)\n    for iv in merged:\n        print(f\"{iv[0]} {iv[1]}\")\n",
    "python_class": "class Solution:\n    def merge(self, intervals: List[List[int]]) -> List[List[int]]:\n        if not intervals: return []\n        intervals.sort(key=lambda x: x[0])\n        merged = [intervals[0]]\n        for cur in intervals[1:]:\n            if cur[0] <= merged[-1][1]:\n                merged[-1][1] = max(merged[-1][1], cur[1])\n            else:\n                merged.append(cur)\n        return merged\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int[][] merge(int[][] intervals) {\n        if (intervals.length <= 1) return intervals;\n        Arrays.sort(intervals, (a, b) -> Integer.compare(a[0], b[0]));\n        List<int[]> res = new ArrayList<>();\n        int[] curr = intervals[0];\n        res.add(curr);\n        for (int[] next : intervals) {\n            if (next[0] <= curr[1]) {\n                curr[1] = Math.max(curr[1], next[1]);\n            } else {\n                curr = next;\n                res.add(curr);\n            }\n        }\n        return res.toArray(new int[res.size()][]);\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct { int start, end; } Interval;\n\nint compare(const void* a, const void* b) {\n    Interval* ia = (Interval*)a;\n    Interval* ib = (Interval*)b;\n    return ia->start - ib->start;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1 || n <= 0) return 0;\n    Interval intervals[n];\n    for (int i = 0; i < n; i++) scanf(\"%d %d\", &intervals[i].start, &intervals[i].end);\n    qsort(intervals, n, sizeof(Interval), compare);\n    Interval res[n];\n    int count = 0;\n    res[0] = intervals[0];\n    count = 1;\n    for (int i = 1; i < n; i++) {\n        if (intervals[i].start <= res[count - 1].end) {\n            if (intervals[i].end > res[count - 1].end) res[count - 1].end = intervals[i].end;\n        } else {\n            res[count++] = intervals[i];\n        }\n    }\n    for (int i = 0; i < count; i++) {\n        printf(\"%d %d\\n\", res[i].start, res[i].end);\n    }\n    return 0;\n}"
  },
  "number_of_islands": {
    "python": "import sys\nsys.setrecursionlimit(200000)\n\ndata = sys.stdin.read().split()\nif data:\n    m = int(data[0])\n    n = int(data[1])\n    grid = []\n    idx = 2\n    for _ in range(m):\n        grid.append(list(data[idx:idx+n]))\n        idx += n\n    count = 0\n    def dfs(r, c):\n        if r < 0 or r >= m or c < 0 or c >= n or grid[r][c] != '1':\n            return\n        grid[r][c] = '0'\n        dfs(r + 1, c)\n        dfs(r - 1, c)\n        dfs(r, c + 1)\n        dfs(r, c - 1)\n    for r in range(m):\n        for c in range(n):\n            if grid[r][c] == '1':\n                count += 1\n                dfs(r, c)\n    print(count)\n",
    "python_class": "class Solution:\n    def numIslands(self, grid: List[List[str]]) -> int:\n        if not grid: return 0\n        m, n = len(grid), len(grid[0])\n        count = 0\n        def dfs(r, c):\n            if r < 0 or r >= m or c < 0 or c >= n or grid[r][c] != '1':\n                return\n            grid[r][c] = '0'\n            dfs(r + 1, c)\n            dfs(r - 1, c)\n            dfs(r, c + 1)\n            dfs(r, c - 1)\n        for r in range(m):\n            for c in range(n):\n                if grid[r][c] == '1':\n                    count += 1\n                    dfs(r, c)\n        return count\n",
    "java": "class Solution {\n    public int numIslands(char[][] grid) {\n        if (grid == null || grid.length == 0) return 0;\n        int m = grid.length, n = grid[0].length;\n        int count = 0;\n        for (int r = 0; r < m; r++) {\n            for (int c = 0; c < n; c++) {\n                if (grid[r][c] == '1') {\n                    count++;\n                    dfs(grid, r, c, m, n);\n                }\n            }\n        }\n        return count;\n    }\n    private void dfs(char[][] grid, int r, int c, int m, int n) {\n        if (r < 0 || r >= m || c < 0 || c >= n || grid[r][c] != '1') return;\n        grid[r][c] = '0';\n        dfs(grid, r + 1, c, m, n);\n        dfs(grid, r - 1, c, m, n);\n        dfs(grid, r, c + 1, m, n);\n        dfs(grid, r, c - 1, m, n);\n    }\n}",
    "c": "#include <stdio.h>\n\nvoid dfs(int m, int n, char grid[m][n], int r, int c) {\n    if (r < 0 || r >= m || c < 0 || c >= n || grid[r][c] != '1') return;\n    grid[r][c] = '0';\n    dfs(m, n, grid, r + 1, c);\n    dfs(m, n, grid, r - 1, c);\n    dfs(m, n, grid, r, c + 1);\n    dfs(m, n, grid, r, c - 1);\n}\n\nint main() {\n    int m, n;\n    if (scanf(\"%d %d\", &m, &n) != 2) return 0;\n    char grid[m][n];\n    for (int i = 0; i < m; i++) {\n        for (int j = 0; j < n; j++) {\n            scanf(\" %c\", &grid[i][j]);\n        }\n    }\n    int count = 0;\n    for (int i = 0; i < m; i++) {\n        for (int j = 0; j < n; j++) {\n            if (grid[i][j] == '1') {\n                count++;\n                dfs(m, n, grid, i, j);\n            }\n        }\n    }\n    printf(\"%d\\n\", count);\n    return 0;\n}"
  },
  "top_k_frequent": {
    "python": "import sys\nfrom collections import Counter\n\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    k = int(data[1])\n    nums = [int(x) for x in data[2:2+n]]\n    counts = Counter(nums)\n    most_common = [str(x[0]) for x in counts.most_common(k)]\n    print(' '.join(most_common))\n",
    "python_class": "from collections import Counter\n\nclass Solution:\n    def topKFrequent(self, nums: List[int], k: int) -> List[int]:\n        count = Counter(nums)\n        return [item[0] for item in count.most_common(k)]\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int[] topKFrequent(int[] nums, int k) {\n        Map<Integer, Integer> count = new HashMap<>();\n        for (int x : nums) count.put(x, count.getOrDefault(x, 0) + 1);\n        PriorityQueue<Integer> pq = new PriorityQueue<>((a, b) -> count.get(a) - count.get(b));\n        for (int key : count.keySet()) {\n            pq.offer(key);\n            if (pq.size() > k) pq.poll();\n        }\n        int[] res = new int[k];\n        for (int i = k - 1; i >= 0; i--) res[i] = pq.poll();\n        return res;\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct { int val, count, first_seen; } Pair;\n\nint cmp(const void* a, const void* b) {\n    Pair* pa = (Pair*)a;\n    Pair* pb = (Pair*)b;\n    if (pb->count != pa->count) return pb->count - pa->count;\n    return pa->first_seen - pb->first_seen;\n}\n\nint main() {\n    int n, k;\n    if (scanf(\"%d %d\", &n, &k) != 2) return 0;\n    Pair pairs[n];\n    int num_pairs = 0;\n    for (int i = 0; i < n; i++) {\n        int x; scanf(\"%d\", &x);\n        int found = 0;\n        for (int j = 0; j < num_pairs; j++) {\n            if (pairs[j].val == x) { pairs[j].count++; found = 1; break; }\n        }\n        if (!found) {\n            pairs[num_pairs].val = x;\n            pairs[num_pairs].count = 1;\n            pairs[num_pairs].first_seen = i;\n            num_pairs++;\n        }\n    }\n    qsort(pairs, num_pairs, sizeof(Pair), cmp);\n    for (int i = 0; i < k; i++) {\n        printf(\"%d%c\", pairs[i].val, (i == k - 1) ? '\\n' : ' ');\n    }\n    return 0;\n}"
  },
  "trapping_rain_water": {
    "python": "import sys\n\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    height = [int(x) for x in data[1:n+1]]\n    l, r = 0, n - 1\n    l_max = r_max = 0\n    water = 0\n    while l < r:\n        if height[l] < height[r]:\n            if height[l] >= l_max: l_max = height[l]\n            else: water += l_max - height[l]\n            l += 1\n        else:\n            if height[r] >= r_max: r_max = height[r]\n            else: water += r_max - height[r]\n            r -= 1\n    print(water)\n",
    "python_class": "class Solution:\n    def trap(self, height: List[int]) -> int:\n        if not height: return 0\n        l, r = 0, len(height) - 1\n        l_max = r_max = 0\n        water = 0\n        while l < r:\n            if height[l] < height[r]:\n                if height[l] >= l_max: l_max = height[l]\n                else: water += l_max - height[l]\n                l += 1\n            else:\n                if height[r] >= r_max: r_max = height[r]\n                else: water += r_max - height[r]\n                r -= 1\n        return water\n",
    "java": "class Solution {\n    public int trap(int[] height) {\n        if (height == null || height.length == 0) return 0;\n        int l = 0, r = height.length - 1;\n        int l_max = 0, r_max = 0, water = 0;\n        while (l < r) {\n            if (height[l] < height[r]) {\n                if (height[l] >= l_max) l_max = height[l];\n                else water += l_max - height[l];\n                l++;\n            } else {\n                if (height[r] >= r_max) r_max = height[r];\n                else water += r_max - height[r];\n                r--;\n            }\n        }\n        return water;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1 || n <= 0) { printf(\"0\\n\"); return 0; }\n    int height[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &height[i]);\n    int l = 0, r = n - 1;\n    int left_max = 0, right_max = 0;\n    long total_water = 0;\n    while (l < r) {\n        if (height[l] < height[r]) {\n            if (height[l] >= left_max) left_max = height[l];\n            else total_water += left_max - height[l];\n            l++;\n        } else {\n            if (height[r] >= right_max) right_max = height[r];\n            else total_water += right_max - height[r];\n            r--;\n        }\n    }\n    printf(\"%ld\\n\", total_water);\n    return 0;\n}"
  },
  "minimum_window_substring": {
    "python": "import sys\nfrom collections import Counter\n\nlines = sys.stdin.read().splitlines()\nif len(lines) >= 2:\n    s, t = lines[0].strip(), lines[1].strip()\n    if not s or not t:\n        print('')\n    else:\n        target = Counter(t)\n        required = len(target)\n        window = {}\n        formed = 0\n        l = 0\n        ans = (float('inf'), None, None)\n        for r, ch in enumerate(s):\n            window[ch] = window.get(ch, 0) + 1\n            if ch in target and window[ch] == target[ch]:\n                formed += 1\n            while l <= r and formed == required:\n                if (r - l + 1) < ans[0]:\n                    ans = (r - l + 1, l, r)\n                ch_l = s[l]\n                window[ch_l] -= 1\n                if ch_l in target and window[ch_l] < target[ch_l]:\n                    formed -= 1\n                l += 1\n        print(s[ans[1]:ans[2]+1] if ans[0] != float('inf') else '')\n",
    "python_class": "from collections import Counter\n\nclass Solution:\n    def minWindow(self, s: str, t: str) -> str:\n        if not s or not t: return \"\"\n        target = Counter(t)\n        required = len(target)\n        window = {}\n        formed = 0\n        l = 0\n        ans = (float('inf'), None, None)\n        for r, ch in enumerate(s):\n            window[ch] = window.get(ch, 0) + 1\n            if ch in target and window[ch] == target[ch]:\n                formed += 1\n            while l <= r and formed == required:\n                if (r - l + 1) < ans[0]:\n                    ans = (r - l + 1, l, r)\n                ch_l = s[l]\n                window[ch_l] -= 1\n                if ch_l in target and window[ch_l] < target[ch_l]:\n                    formed -= 1\n                l += 1\n        return s[ans[1]:ans[2]+1] if ans[0] != float('inf') else \"\"\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public String minWindow(String s, String t) {\n        if (s.length() == 0 || t.length() == 0) return \"\";\n        Map<Character, Integer> dictT = new HashMap<>();\n        for (char c : t.toCharArray()) dictT.put(c, dictT.getOrDefault(c, 0) + 1);\n        int required = dictT.size();\n        int l = 0, r = 0, formed = 0;\n        Map<Character, Integer> windowCounts = new HashMap<>();\n        int[] ans = {-1, 0, 0};\n        while (r < s.length()) {\n            char c = s.charAt(r);\n            windowCounts.put(c, windowCounts.getOrDefault(c, 0) + 1);\n            if (dictT.containsKey(c) && windowCounts.get(c).intValue() == dictT.get(c).intValue()) {\n                formed++;\n            }\n            while (l <= r && formed == required) {\n                if (ans[0] == -1 || r - l + 1 < ans[0]) {\n                    ans[0] = r - l + 1;\n                    ans[1] = l;\n                    ans[2] = r;\n                }\n                char leftChar = s.charAt(l);\n                windowCounts.put(leftChar, windowCounts.get(leftChar) - 1);\n                if (dictT.containsKey(leftChar) && windowCounts.get(leftChar) < dictT.get(leftChar)) {\n                    formed--;\n                }\n                l++;\n            }\n            r++;\n        }\n        return ans[0] == -1 ? \"\" : s.substring(ans[1], ans[2] + 1);\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100005], t[100005];\n    if (scanf(\"%s %s\", s, t) != 2) return 0;\n    int count[256] = {0};\n    for (int i = 0; t[i]; i++) count[(unsigned char)t[i]]++;\n    int required = 0;\n    for (int i = 0; i < 256; i++) if (count[i] > 0) required++;\n\n    int window[256] = {0};\n    int formed = 0, l = 0, min_len = 1000000, start = 0;\n\n    for (int r = 0; s[r]; r++) {\n        unsigned char c = (unsigned char)s[r];\n        window[c]++;\n        if (count[c] > 0 && window[c] == count[c]) formed++;\n\n        while (l <= r && formed == required) {\n            if (r - l + 1 < min_len) {\n                min_len = r - l + 1;\n                start = l;\n            }\n            unsigned char cl = (unsigned char)s[l];\n            window[cl]--;\n            if (count[cl] > 0 && window[cl] < count[cl]) formed--;\n            l++;\n        }\n    }\n    if (min_len <= 100000) {\n        s[start + min_len] = '\\0';\n        printf(\"%s\\n\", s + start);\n    } else {\n        printf(\"\\n\");\n    }\n    return 0;\n}"
  },
  "merge_k_sorted_lists": {
    "python": "import sys\nimport heapq\n\ndata = sys.stdin.read().split()\nif data:\n    k = int(data[0])\n    all_nums = []\n    idx = 1\n    for _ in range(k):\n        length = int(data[idx])\n        idx += 1\n        for _ in range(length):\n            all_nums.append(int(data[idx]))\n            idx += 1\n    all_nums.sort()\n    print(' '.join(map(str, all_nums)))\n",
    "python_class": "import heapq\n\nclass Solution:\n    def mergeKLists(self, lists: List[Optional[ListNode]]) -> Optional[ListNode]:\n        heap = []\n        for i, node in enumerate(lists):\n            if node:\n                heapq.heappush(heap, (node.val, i, node))\n        dummy = ListNode(0)\n        curr = dummy\n        while heap:\n            val, i, node = heapq.heappop(heap)\n            curr.next = node\n            curr = curr.next\n            if node.next:\n                heapq.heappush(heap, (node.next.val, i, node.next))\n        return dummy.next\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public ListNode mergeKLists(ListNode[] lists) {\n        if (lists == null || lists.length == 0) return null;\n        PriorityQueue<ListNode> pq = new PriorityQueue<>((a, b) -> a.val - b.val);\n        for (ListNode node : lists) {\n            if (node != null) pq.offer(node);\n        }\n        ListNode dummy = new ListNode(0);\n        ListNode curr = dummy;\n        while (!pq.isEmpty()) {\n            ListNode node = pq.poll();\n            curr.next = node;\n            curr = curr.next;\n            if (node.next != null) pq.offer(node.next);\n        }\n        return dummy.next;\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint cmp(const void* a, const void* b) { return (*(int*)a - *(int*)b); }\n\nint main() {\n    int k;\n    if (scanf(\"%d\", &k) != 1 || k <= 0) return 0;\n    int all[100005];\n    int total = 0;\n    for (int i = 0; i < k; i++) {\n        int len; scanf(\"%d\", &len);\n        for (int j = 0; j < len; j++) scanf(\"%d\", &all[total++]);\n    }\n    qsort(all, total, sizeof(int), cmp);\n    for (int i = 0; i < total; i++) {\n        printf(\"%d%c\", all[i], (i == total - 1) ? '\\n' : ' ');\n    }\n    return 0;\n}"
  },
  "word_ladder": {
    "python": "import sys\nfrom collections import deque\n\ndata = sys.stdin.read().split()\nif data:\n    beginWord = data[0]\n    endWord = data[1]\n    n = int(data[2])\n    wordList = data[3:3+n]\n    if endWord not in wordList:\n        print(0)\n    else:\n        wordSet = set(wordList)\n        queue = deque([(beginWord, 1)])\n        visited = {beginWord}\n        found = False\n        while queue:\n            word, steps = queue.popleft()\n            if word == endWord:\n                print(steps)\n                found = True\n                break\n            for i in range(len(word)):\n                for c in 'abcdefghijklmnopqrstuvwxyz':\n                    next_w = word[:i] + c + word[i+1:]\n                    if next_w in wordSet and next_w not in visited:\n                        visited.add(next_w)\n                        queue.append((next_w, steps + 1))\n        if not found:\n            print(0)\n",
    "python_class": "from collections import deque\n\nclass Solution:\n    def ladderLength(self, beginWord: str, endWord: str, wordList: List[str]) -> int:\n        wordSet = set(wordList)\n        if endWord not in wordSet:\n            return 0\n        queue = deque([(beginWord, 1)])\n        visited = {beginWord}\n        while queue:\n            word, steps = queue.popleft()\n            if word == endWord:\n                return steps\n            for i in range(len(word)):\n                for c in 'abcdefghijklmnopqrstuvwxyz':\n                    next_w = word[:i] + c + word[i+1:]\n                    if next_w in wordSet and next_w not in visited:\n                        visited.add(next_w)\n                        queue.append((next_w, steps + 1))\n        return 0\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int ladderLength(String beginWord, String endWord, List<String> wordList) {\n        Set<String> set = new HashSet<>(wordList);\n        if (!set.contains(endWord)) return 0;\n        Queue<String> queue = new LinkedList<>();\n        queue.offer(beginWord);\n        int level = 1;\n        while (!queue.isEmpty()) {\n            int size = queue.size();\n            for (int k = 0; k < size; k++) {\n                String word = queue.poll();\n                if (word.equals(endWord)) return level;\n                char[] chs = word.toCharArray();\n                for (int i = 0; i < chs.length; i++) {\n                    char orig = chs[i];\n                    for (char c = 'a'; c <= 'z'; c++) {\n                        chs[i] = c;\n                        String str = new String(chs);\n                        if (set.remove(str)) queue.offer(str);\n                    }\n                    chs[i] = orig;\n                }\n            }\n            level++;\n        }\n        return 0;\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n#include <stdbool.h>\n\nint main() {\n    char begin[105], end[105];\n    if (scanf(\"%s %s\", begin, end) != 2) return 0;\n    int n; scanf(\"%d\", &n);\n    char words[n][105];\n    for (int i = 0; i < n; i++) scanf(\"%s\", words[i]);\n    int q[5005], dist[5005]; bool visited[5005] = {false};\n    int front = 0, rear = 0;\n    int end_idx = -1;\n    for (int i = 0; i < n; i++) {\n        if (strcmp(words[i], end) == 0) end_idx = i;\n    }\n    if (end_idx == -1) { printf(\"0\\n\"); return 0; }\n    for (int i = 0; i < n; i++) {\n        int diff = 0;\n        for (int j = 0; begin[j]; j++) if (begin[j] != words[i][j]) diff++;\n        if (diff == 1) {\n            q[rear] = i; dist[rear] = 2; visited[i] = true; rear++;\n        }\n    }\n    while (front < rear) {\n        int curr = q[front]; int d = dist[front++];\n        if (curr == end_idx) { printf(\"%d\\n\", d); return 0; }\n        for (int i = 0; i < n; i++) {\n            if (!visited[i]) {\n                int diff = 0;\n                for (int j = 0; words[curr][j]; j++) if (words[curr][j] != words[i][j]) diff++;\n                if (diff == 1) {\n                    visited[i] = true;\n                    q[rear] = i; dist[rear] = d + 1; rear++;\n                }\n            }\n        }\n    }\n    printf(\"0\\n\");\n    return 0;\n}"
  },
  "median_two_sorted_arrays": {
    "python": "import sys\n\ndata = sys.stdin.read().split()\nif data:\n    m = int(data[0])\n    n = int(data[1])\n    nums1 = [int(x) for x in data[2:2+m]]\n    nums2 = [int(x) for x in data[2+m:2+m+n]]\n    merged = sorted(nums1 + nums2)\n    total = len(merged)\n    if total % 2 == 1:\n        print(f\"{merged[total // 2]:.1f}\")\n    else:\n        med = (merged[total // 2 - 1] + merged[total // 2]) / 2.0\n        print(f\"{med:.1f}\")\n",
    "python_class": "class Solution:\n    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:\n        merged = sorted(nums1 + nums2)\n        total = len(merged)\n        if total % 2 == 1:\n            return float(merged[total // 2])\n        return (merged[total // 2 - 1] + merged[total // 2]) / 2.0\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public double findMedianSortedArrays(int[] nums1, int[] nums2) {\n        int m = nums1.length, n = nums2.length;\n        int[] merged = new int[m + n];\n        int i = 0, j = 0, k = 0;\n        while (i < m && j < n) merged[k++] = (nums1[i] < nums2[j]) ? nums1[i++] : nums2[j++];\n        while (i < m) merged[k++] = nums1[i++];\n        while (j < n) merged[k++] = nums2[j++];\n        int total = m + n;\n        if (total % 2 == 1) return (double) merged[total / 2];\n        return (merged[total / 2 - 1] + merged[total / 2]) / 2.0;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n, m;\n    if (scanf(\"%d %d\", &n, &m) != 2) return 0;\n    int a[n], b[m];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &a[i]);\n    for (int i = 0; i < m; i++) scanf(\"%d\", &b[i]);\n    int total = n + m;\n    if (total == 0) { printf(\"0.0\\n\"); return 0; }\n    int merged[total];\n    int i = 0, j = 0, k = 0;\n    while (i < n && j < m) merged[k++] = (a[i] < b[j]) ? a[i++] : b[j++];\n    while (i < n) merged[k++] = a[i++];\n    while (j < m) merged[k++] = b[j++];\n    if (total % 2 == 1) {\n        printf(\"%.1f\\n\", (double)merged[total / 2]);\n    } else {\n        printf(\"%.1f\\n\", (double)(merged[total / 2 - 1] + merged[total / 2]) / 2.0);\n    }\n    return 0;\n}"
  },
  "palindrome_number": {
    "python": "import sys\nx = int(sys.stdin.read().strip())\ns = str(x)\nprint(\"true\" if s == s[::-1] else \"false\")\n",
    "python_class": "class Solution:\n    def isPalindrome(self, x: int) -> bool:\n        if x < 0:\n            return False\n        s = str(x)\n        return s == s[::-1]\n",
    "java": "class Solution {\n    public boolean isPalindrome(int x) {\n        if (x < 0) return false;\n        String s = String.valueOf(x);\n        return s.equals(new StringBuilder(s).reverse().toString());\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdbool.h>\n\nint main() {\n    int x;\n    if (scanf(\"%d\", &x) != 1) return 0;\n    if (x < 0) {\n        printf(\"false\\n\");\n        return 0;\n    }\n    long orig = x, rev = 0;\n    while (x > 0) {\n        rev = rev * 10 + (x % 10);\n        x /= 10;\n    }\n    if (orig == rev) printf(\"true\\n\");\n    else printf(\"false\\n\");\n    return 0;\n}"
  },
  "fizz_buzz": {
    "python": "import sys\nn = int(sys.stdin.read().strip())\nres = []\nfor i in range(1, n + 1):\n    if i % 15 == 0: res.append(\"FizzBuzz\")\n    elif i % 3 == 0: res.append(\"Fizz\")\n    elif i % 5 == 0: res.append(\"Buzz\")\n    else: res.append(str(i))\nprint(\" \".join(res))\n",
    "python_class": "class Solution:\n    def fizzBuzz(self, n: int) -> List[str]:\n        res = []\n        for i in range(1, n + 1):\n            if i % 15 == 0: res.append(\"FizzBuzz\")\n            elif i % 3 == 0: res.append(\"Fizz\")\n            elif i % 5 == 0: res.append(\"Buzz\")\n            else: res.append(str(i))\n        return res\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public List<String> fizzBuzz(int n) {\n        List<String> res = new ArrayList<>();\n        for (int i = 1; i <= n; i++) {\n            if (i % 15 == 0) res.add(\"FizzBuzz\");\n            else if (i % 3 == 0) res.add(\"Fizz\");\n            else if (i % 5 == 0) res.add(\"Buzz\");\n            else res.add(String.valueOf(i));\n        }\n        return res;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    for (int i = 1; i <= n; i++) {\n        if (i % 15 == 0) printf(\"FizzBuzz\");\n        else if (i % 3 == 0) printf(\"Fizz\");\n        else if (i % 5 == 0) printf(\"Buzz\");\n        else printf(\"%d\", i);\n        if (i < n) printf(\" \");\n    }\n    printf(\"\\n\");\n    return 0;\n}"
  },
  "length_of_last_word": {
    "python": "import sys\ns = sys.stdin.read().strip()\nwords = s.split()\nprint(len(words[-1]) if words else 0)\n",
    "python_class": "class Solution:\n    def lengthOfLastWord(self, s: str) -> int:\n        words = s.strip().split()\n        return len(words[-1]) if words else 0\n",
    "java": "class Solution {\n    public int lengthOfLastWord(String s) {\n        String trimmed = s.trim();\n        int lastSpace = trimmed.lastIndexOf(' ');\n        if (lastSpace == -1) return trimmed.length();\n        return trimmed.length() - 1 - lastSpace;\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100005];\n    if (!fgets(s, sizeof(s), stdin)) { printf(\"0\\n\"); return 0; }\n    int len = strlen(s);\n    while (len > 0 && (s[len - 1] == '\\n' || s[len - 1] == '\\r' || s[len - 1] == ' ')) {\n        s[--len] = '\\0';\n    }\n    int count = 0;\n    while (len > 0 && s[len - 1] != ' ') {\n        count++;\n        len--;\n    }\n    printf(\"%d\\n\", count);\n    return 0;\n}"
  },
  "move_zeroes": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    nums = [int(x) for x in data[1:n+1]]\n    non_zeros = [x for x in nums if x != 0]\n    res = non_zeros + [0] * (n - len(non_zeros))\n    print(\" \".join(map(str, res)))\n",
    "python_class": "class Solution:\n    def moveZeroes(self, nums: List[int]) -> None:\n        insert_pos = 0\n        for x in nums:\n            if x != 0:\n                nums[insert_pos] = x\n                insert_pos += 1\n        while insert_pos < len(nums):\n            nums[insert_pos] = 0\n            insert_pos += 1\n",
    "java": "class Solution {\n    public void moveZeroes(int[] nums) {\n        int pos = 0;\n        for (int x : nums) {\n            if (x != 0) nums[pos++] = x;\n        }\n        while (pos < nums.length) {\n            nums[pos++] = 0;\n        }\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1 || n <= 0) return 0;\n    int nums[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int pos = 0;\n    for (int i = 0; i < n; i++) {\n        if (nums[i] != 0) nums[pos++] = nums[i];\n    }\n    while (pos < n) nums[pos++] = 0;\n    for (int i = 0; i < n; i++) {\n        printf(\"%d%c\", nums[i], (i == n - 1) ? '\\n' : ' ');\n    }\n    return 0;\n}"
  },
  "merge_sorted_array": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    m, n = int(data[0]), int(data[1])\n    nums1 = [int(x) for x in data[2:2+m]]\n    nums2 = [int(x) for x in data[2+m:2+m+n]]\n    merged = sorted(nums1 + nums2)\n    print(\" \".join(map(str, merged)))\n",
    "python_class": "class Solution:\n    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:\n        p1, p2, p = m - 1, n - 1, m + n - 1\n        while p1 >= 0 and p2 >= 0:\n            if nums1[p1] > nums2[p2]:\n                nums1[p] = nums1[p1]\n                p1 -= 1\n            else:\n                nums1[p] = nums2[p2]\n                p2 -= 1\n            p -= 1\n        while p2 >= 0:\n            nums1[p] = nums2[p2]\n            p2 -= 1\n            p -= 1\n",
    "java": "class Solution {\n    public void merge(int[] nums1, int m, int[] nums2, int n) {\n        int p1 = m - 1, p2 = n - 1, p = m + n - 1;\n        while (p1 >= 0 && p2 >= 0) {\n            if (nums1[p1] > nums2[p2]) nums1[p--] = nums1[p1--];\n            else nums1[p--] = nums2[p2--];\n        }\n        while (p2 >= 0) nums1[p--] = nums2[p2--];\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint cmp(const void* a, const void* b) { return (*(int*)a - *(int*)b); }\n\nint main() {\n    int m, n;\n    if (scanf(\"%d %d\", &m, &n) != 2) return 0;\n    int total = m + n;\n    int all[total];\n    for (int i = 0; i < m; i++) scanf(\"%d\", &all[i]);\n    for (int i = 0; i < n; i++) scanf(\"%d\", &all[m + i]);\n    qsort(all, total, sizeof(int), cmp);\n    for (int i = 0; i < total; i++) {\n        printf(\"%d%c\", all[i], (i == total - 1) ? '\\n' : ' ');\n    }\n    return 0;\n}"
  },
  "add_two_numbers": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    n1 = int(data[0])\n    l1 = [int(x) for x in data[1:n1+1]]\n    n2 = int(data[n1+1])\n    l2 = [int(x) for x in data[n1+2:n1+2+n2]]\n    res = []\n    carry = 0\n    i, j = 0, 0\n    while i < n1 or j < n2 or carry:\n        s = carry\n        if i < n1: s += l1[i]; i += 1\n        if j < n2: s += l2[j]; j += 1\n        res.append(str(s % 10))\n        carry = s // 10\n    print(\" \".join(res))\n",
    "python_class": "class Solution:\n    def addTwoNumbers(self, l1: Optional[ListNode], l2: Optional[ListNode]) -> Optional[ListNode]:\n        dummy = ListNode(0)\n        curr = dummy\n        carry = 0\n        while l1 or l2 or carry:\n            val1 = l1.val if l1 else 0\n            val2 = l2.val if l2 else 0\n            total = val1 + val2 + carry\n            carry = total // 10\n            curr.next = ListNode(total % 10)\n            curr = curr.next\n            if l1: l1 = l1.next\n            if l2: l2 = l2.next\n        return dummy.next\n",
    "java": "class Solution {\n    public ListNode addTwoNumbers(ListNode l1, ListNode l2) {\n        ListNode dummy = new ListNode(0);\n        ListNode curr = dummy;\n        int carry = 0;\n        while (l1 != null || l2 != null || carry != 0) {\n            int sum = carry;\n            if (l1 != null) { sum += l1.val; l1 = l1.next; }\n            if (l2 != null) { sum += l2.val; l2 = l2.next; }\n            carry = sum / 10;\n            curr.next = new ListNode(sum % 10);\n            curr = curr.next;\n        }\n        return dummy.next;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n1;\n    if (scanf(\"%d\", &n1) != 1) return 0;\n    int l1[n1];\n    for (int i = 0; i < n1; i++) scanf(\"%d\", &l1[i]);\n    int n2;\n    scanf(\"%d\", &n2);\n    int l2[n2];\n    for (int i = 0; i < n2; i++) scanf(\"%d\", &l2[i]);\n\n    int res[205];\n    int count = 0, carry = 0, i = 0, j = 0;\n    while (i < n1 || j < n2 || carry) {\n        int sum = carry;\n        if (i < n1) sum += l1[i++];\n        if (j < n2) sum += l2[j++];\n        res[count++] = sum % 10;\n        carry = sum / 10;\n    }\n    for (int k = 0; k < count; k++) {\n        printf(\"%d%c\", res[k], (k == count - 1) ? '\\n' : ' ');\n    }\n    return 0;\n}"
  },
  "rotate_array": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    n, k = int(data[0]), int(data[1])\n    nums = [int(x) for x in data[2:2+n]]\n    k = k % n\n    if k > 0: nums = nums[-k:] + nums[:-k]\n    print(\" \".join(map(str, nums)))\n",
    "python_class": "class Solution:\n    def rotate(self, nums: List[int], k: int) -> None:\n        n = len(nums)\n        k = k % n\n        nums[:] = nums[-k:] + nums[:-k]\n",
    "java": "class Solution {\n    public void rotate(int[] nums, int k) {\n        int n = nums.length;\n        if (n == 0) return;\n        k %= n;\n        reverse(nums, 0, n - 1);\n        reverse(nums, 0, k - 1);\n        reverse(nums, k, n - 1);\n    }\n    private void reverse(int[] a, int l, int r) {\n        while (l < r) {\n            int t = a[l]; a[l] = a[r]; a[r] = t;\n            l++; r--;\n        }\n    }\n}",
    "c": "#include <stdio.h>\n\nvoid rev(int* a, int l, int r) {\n    while (l < r) {\n        int t = a[l]; a[l] = a[r]; a[r] = t;\n        l++; r--;\n    }\n}\n\nint main() {\n    int n, k;\n    if (scanf(\"%d %d\", &n, &k) != 2 || n <= 0) return 0;\n    int a[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &a[i]);\n    k %= n;\n    rev(a, 0, n - 1);\n    rev(a, 0, k - 1);\n    rev(a, k, n - 1);\n    for (int i = 0; i < n; i++) {\n        printf(\"%d%c\", a[i], (i == n - 1) ? '\\n' : ' ');\n    }\n    return 0;\n}"
  },
  "coin_change": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    n, amount = int(data[0]), int(data[1])\n    coins = [int(x) for x in data[2:2+n]]\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for coin in coins:\n        for x in range(coin, amount + 1):\n            dp[x] = min(dp[x], dp[x - coin] + 1)\n    print(dp[amount] if dp[amount] != float('inf') else -1)\n",
    "python_class": "class Solution:\n    def coinChange(self, coins: List[int], amount: int) -> int:\n        dp = [float('inf')] * (amount + 1)\n        dp[0] = 0\n        for coin in coins:\n            for x in range(coin, amount + 1):\n                dp[x] = min(dp[x], dp[x - coin] + 1)\n        return dp[amount] if dp[amount] != float('inf') else -1\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int coinChange(int[] coins, int amount) {\n        int[] dp = new int[amount + 1];\n        Arrays.fill(dp, amount + 1);\n        dp[0] = 0;\n        for (int coin : coins) {\n            for (int x = coin; x <= amount; x++) {\n                dp[x] = Math.min(dp[x], dp[x - coin] + 1);\n            }\n        }\n        return dp[amount] > amount ? -1 : dp[amount];\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n, amount;\n    if (scanf(\"%d %d\", &n, &amount) != 2) return 0;\n    int coins[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &coins[i]);\n    int dp[amount + 1];\n    for (int i = 0; i <= amount; i++) dp[i] = amount + 1;\n    dp[0] = 0;\n    for (int i = 0; i < n; i++) {\n        int c = coins[i];\n        for (int x = c; x <= amount; x++) {\n            if (dp[x - c] + 1 < dp[x]) dp[x] = dp[x - c] + 1;\n        }\n    }\n    printf(\"%d\\n\", dp[amount] > amount ? -1 : dp[amount]);\n    return 0;\n}"
  },
  "binary_tree": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    if n > 0:\n        nodes = [int(x) for x in data[1:n+1]]\n        idx = 0\n        level_size = 1\n        while idx < n:\n            curr_level = nodes[idx:min(idx + level_size, n)]\n            print(\" \".join(map(str, curr_level)))\n            idx += level_size\n            level_size *= 2\n",
    "python_class": "from collections import deque\n\nclass Solution:\n    def levelOrder(self, root: Optional[TreeNode]) -> List[List[int]]:\n        if not root: return []\n        res = []\n        queue = deque([root])\n        while queue:\n            level = []\n            for _ in range(len(queue)):\n                node = queue.popleft()\n                level.append(node.val)\n                if node.left: queue.append(node.left)\n                if node.right: queue.append(node.right)\n            res.append(level)\n        return res\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public List<List<Integer>> levelOrder(TreeNode root) {\n        List<List<Integer>> res = new ArrayList<>();\n        if (root == null) return res;\n        Queue<TreeNode> q = new LinkedList<>();\n        q.offer(root);\n        while (!q.isEmpty()) {\n            int size = q.size();\n            List<Integer> level = new ArrayList<>();\n            for (int i = 0; i < size; i++) {\n                TreeNode cur = q.poll();\n                level.add(cur.val);\n                if (cur.left != null) q.offer(cur.left);\n                if (cur.right != null) q.offer(cur.right);\n            }\n            res.add(level);\n        }\n        return res;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1 || n <= 0) return 0;\n    int nodes[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nodes[i]);\n    int idx = 0, level_size = 1;\n    while (idx < n) {\n        int end = (idx + level_size < n) ? idx + level_size : n;\n        for (int i = idx; i < end; i++) {\n            printf(\"%d%c\", nodes[i], (i == end - 1) ? '\\n' : ' ');\n        }\n        idx = end;\n        level_size *= 2;\n    }\n    return 0;\n}"
  },
  "combination_sum": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    n, target = int(data[0]), int(data[1])\n    candidates = sorted([int(x) for x in data[2:2+n]])\n    res = []\n    def backtrack(remain, combo, start):\n        if remain == 0:\n            res.append(list(combo))\n            return\n        if remain < 0:\n            return\n        for i in range(start, len(candidates)):\n            combo.append(candidates[i])\n            backtrack(remain - candidates[i], combo, i)\n            combo.pop()\n    backtrack(target, [], 0)\n    for c in res:\n        print(\" \".join(map(str, c)))\n",
    "python_class": "class Solution:\n    def combinationSum(self, candidates: List[int], target: int) -> List[List[int]]:\n        candidates.sort()\n        res = []\n        def backtrack(remain, combo, start):\n            if remain == 0:\n                res.append(list(combo))\n                return\n            for i in range(start, len(candidates)):\n                if candidates[i] > remain: break\n                combo.append(candidates[i])\n                backtrack(remain - candidates[i], combo, i)\n                combo.pop()\n        backtrack(target, [], 0)\n        return res\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public List<List<Integer>> combinationSum(int[] candidates, int target) {\n        Arrays.sort(candidates);\n        List<List<Integer>> res = new ArrayList<>();\n        backtrack(candidates, target, new ArrayList<>(), 0, res);\n        return res;\n    }\n    private void backtrack(int[] cand, int remain, List<Integer> combo, int start, List<List<Integer>> res) {\n        if (remain == 0) {\n            res.add(new ArrayList<>(combo));\n            return;\n        }\n        for (int i = start; i < cand.length; i++) {\n            if (cand[i] > remain) break;\n            combo.add(cand[i]);\n            backtrack(cand, remain - cand[i], combo, i, res);\n            combo.remove(combo.size() - 1);\n        }\n    }\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint cmp(const void* a, const void* b) { return (*(int*)a - *(int*)b); }\n\nvoid backtrack(int* cand, int n, int remain, int* combo, int comboSize, int start) {\n    if (remain == 0) {\n        for (int i = 0; i < comboSize; i++) {\n            printf(\"%d%c\", combo[i], (i == comboSize - 1) ? '\\n' : ' ');\n        }\n        return;\n    }\n    for (int i = start; i < n; i++) {\n        if (cand[i] > remain) break;\n        combo[comboSize] = cand[i];\n        backtrack(cand, n, remain - cand[i], combo, comboSize + 1, i);\n    }\n}\n\nint main() {\n    int n, target;\n    if (scanf(\"%d %d\", &n, &target) != 2) return 0;\n    int cand[n];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &cand[i]);\n    qsort(cand, n, sizeof(int), cmp);\n    int combo[100];\n    backtrack(cand, n, target, combo, 0, 0);\n    return 0;\n}"
  },
  "largest_rectangle_histogram": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    n = int(data[0])\n    heights = [int(x) for x in data[1:n+1]]\n    stack = []\n    max_area = 0\n    heights.append(0)\n    for i, h in enumerate(heights):\n        while stack and heights[stack[-1]] > h:\n            height = heights[stack.pop()]\n            width = i if not stack else i - stack[-1] - 1\n            max_area = max(max_area, height * width)\n        stack.append(i)\n    print(max_area)\n",
    "python_class": "class Solution:\n    def largestRectangleArea(self, heights: List[int]) -> int:\n        stack = []\n        max_area = 0\n        h_copy = heights + [0]\n        for i, h in enumerate(h_copy):\n            while stack and h_copy[stack[-1]] > h:\n                height = h_copy[stack.pop()]\n                width = i if not stack else i - stack[-1] - 1\n                max_area = max(max_area, height * width)\n            stack.append(i)\n        return max_area\n",
    "java": "import java.util.*;\n\nclass Solution {\n    public int largestRectangleArea(int[] heights) {\n        Stack<Integer> stack = new Stack<>();\n        int maxArea = 0;\n        int n = heights.length;\n        for (int i = 0; i <= n; i++) {\n            int h = (i == n) ? 0 : heights[i];\n            while (!stack.isEmpty() && heights[stack.peek()] > h) {\n                int height = heights[stack.pop()];\n                int width = stack.isEmpty() ? i : i - stack.peek() - 1;\n                maxArea = Math.max(maxArea, height * width);\n            }\n            stack.push(i);\n        }\n        return maxArea;\n    }\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1 || n <= 0) return 0;\n    int h[n + 1];\n    for (int i = 0; i < n; i++) scanf(\"%d\", &h[i]);\n    h[n] = 0;\n    int stack[n + 1];\n    int top = -1;\n    long max_area = 0;\n    for (int i = 0; i <= n; i++) {\n        while (top >= 0 && h[stack[top]] > h[i]) {\n            int height = h[stack[top--]];\n            int width = (top == -1) ? i : i - stack[top] - 1;\n            long area = (long)height * width;\n            if (area > max_area) max_area = area;\n        }\n        stack[++top] = i;\n    }\n    printf(\"%ld\\n\", max_area);\n    return 0;\n}"
  },
  "serialize_deserialize_tree": {
    "python": "import sys\ndata = sys.stdin.read().split()\nif data:\n    nodes = [x for x in data if x != \"null\" and x != \"-1\"]\n    print(\" \".join(nodes))\n",
    "python_class": "from collections import deque\n\nclass Codec:\n    def serialize(self, root: Optional[TreeNode]) -> str:\n        if not root: return \"null\"\n        res = []\n        q = deque([root])\n        while q:\n            node = q.popleft()\n            if node:\n                res.append(str(node.val))\n                q.append(node.left)\n                q.append(node.right)\n            else:\n                res.append(\"null\")\n        while res and res[-1] == \"null\": res.pop()\n        return \" \".join(res)\n\n    def deserialize(self, data: str) -> Optional[TreeNode]:\n        if not data or data == \"null\": return None\n        vals = data.split()\n        root = TreeNode(int(vals[0]))\n        q = deque([root])\n        i = 1\n        while q and i < len(vals):\n            node = q.popleft()\n            if i < len(vals) and vals[i] != \"null\":\n                node.left = TreeNode(int(vals[i]))\n                q.append(node.left)\n            i += 1\n            if i < len(vals) and vals[i] != \"null\":\n                node.right = TreeNode(int(vals[i]))\n                q.append(node.right)\n            i += 1\n        return root\n",
    "java": "import java.util.*;\n\nclass Codec {\n    public String serialize(TreeNode root) {\n        if (root == null) return \"null\";\n        StringBuilder sb = new StringBuilder();\n        Queue<TreeNode> q = new LinkedList<>();\n        q.offer(root);\n        while (!q.isEmpty()) {\n            TreeNode node = q.poll();\n            if (node != null) {\n                sb.append(node.val).append(\" \");\n                q.offer(node.left);\n                q.offer(node.right);\n            } else {\n                sb.append(\"null \");\n            }\n        }\n        return sb.toString().trim();\n    }\n\n    public TreeNode deserialize(String data) {\n        if (data == null || data.equals(\"null\") || data.isEmpty()) return null;\n        String[] vals = data.split(\"\\\\s+\");\n        TreeNode root = new TreeNode(Integer.parseInt(vals[0]));\n        Queue<TreeNode> q = new LinkedList<>();\n        q.offer(root);\n        int i = 1;\n        while (!q.isEmpty() && i < vals.length) {\n            TreeNode node = q.poll();\n            if (i < vals.length && !vals[i].equals(\"null\")) {\n                node.left = new TreeNode(Integer.parseInt(vals[i]));\n                q.offer(node.left);\n            }\n            i++;\n            if (i < vals.length && !vals[i].equals(\"null\")) {\n                node.right = new TreeNode(Integer.parseInt(vals[i]));\n                q.offer(node.right);\n            }\n            i++;\n        }\n        return root;\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char token[100];\n    int first = 1;\n    while (scanf(\"%s\", token) == 1) {\n        if (strcmp(token, \"null\") != 0 && strcmp(token, \"-1\") != 0) {\n            if (!first) printf(\" \");\n            printf(\"%s\", token);\n            first = 0;\n        }\n    }\n    printf(\"\\n\");\n    return 0;\n}"
  },
  "edit_distance": {
    "python": "import sys\nlines = sys.stdin.read().splitlines()\nw1 = lines[0].strip() if len(lines) > 0 else \"\"\nw2 = lines[1].strip() if len(lines) > 1 else \"\"\nm, n = len(w1), len(w2)\ndp = [[0] * (n + 1) for _ in range(m + 1)]\nfor i in range(m + 1): dp[i][0] = i\nfor j in range(n + 1): dp[0][j] = j\nfor i in range(1, m + 1):\n    for j in range(1, n + 1):\n        if w1[i-1] == w2[j-1]: dp[i][j] = dp[i-1][j-1]\n        else: dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\nprint(dp[m][n])\n",
    "python_class": "class Solution:\n    def minDistance(self, word1: str, word2: str) -> int:\n        m, n = len(word1), len(word2)\n        dp = [[0] * (n + 1) for _ in range(m + 1)]\n        for i in range(m + 1): dp[i][0] = i\n        for j in range(n + 1): dp[0][j] = j\n        for i in range(1, m + 1):\n            for j in range(1, n + 1):\n                if word1[i-1] == word2[j-1]: dp[i][j] = dp[i-1][j-1]\n                else: dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n        return dp[m][n]\n",
    "java": "class Solution {\n    public int minDistance(String word1, String word2) {\n        int m = word1.length(), n = word2.length();\n        int[][] dp = new int[m + 1][n + 1];\n        for (int i = 0; i <= m; i++) dp[i][0] = i;\n        for (int j = 0; j <= n; j++) dp[0][j] = j;\n        for (int i = 1; i <= m; i++) {\n            for (int j = 1; j <= n; j++) {\n                if (word1.charAt(i - 1) == word2.charAt(j - 1)) dp[i][j] = dp[i - 1][j - 1];\n                else dp[i][j] = 1 + Math.min(dp[i - 1][j - 1], Math.min(dp[i - 1][j], dp[i][j - 1]));\n            }\n        }\n        return dp[m][n];\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint min3(int a, int b, int c) {\n    int m = a < b ? a : b;\n    return m < c ? m : c;\n}\n\nint main() {\n    char w1[505] = \"\", w2[505] = \"\";\n    if (!fgets(w1, sizeof(w1), stdin)) {}\n    if (!fgets(w2, sizeof(w2), stdin)) {}\n    int m = strlen(w1);\n    while (m > 0 && (w1[m-1] == '\\n' || w1[m-1] == '\\r')) w1[--m] = '\\0';\n    int n = strlen(w2);\n    while (n > 0 && (w2[n-1] == '\\n' || w2[n-1] == '\\r')) w2[--n] = '\\0';\n\n    int dp[m + 1][n + 1];\n    for (int i = 0; i <= m; i++) dp[i][0] = i;\n    for (int j = 0; j <= n; j++) dp[0][j] = j;\n    for (int i = 1; i <= m; i++) {\n        for (int j = 1; j <= n; j++) {\n            if (w1[i-1] == w2[j-1]) dp[i][j] = dp[i-1][j-1];\n            else dp[i][j] = 1 + min3(dp[i-1][j-1], dp[i-1][j], dp[i][j-1]);\n        }\n    }\n    printf(\"%d\\n\", dp[m][n]);\n    return 0;\n}"
  },
  "word_search_ii": {
    "python": "import sys\n\ndata = sys.stdin.read().split()\nif data:\n    m, n = int(data[0]), int(data[1])\n    board = []\n    idx = 2\n    for _ in range(m):\n        board.append(data[idx:idx+n])\n        idx += n\n    k = int(data[idx])\n    idx += 1\n    words = data[idx:idx+k]\n\n    trie = {}\n    for w in words:\n        cur = trie\n        for ch in w:\n            cur = cur.setdefault(ch, {})\n        cur['#'] = w\n\n    res = set()\n    def dfs(r, c, parent, visited):\n        ch = board[r][c]\n        if ch not in parent: return\n        node = parent[ch]\n        if '#' in node:\n            res.add(node['#'])\n        visited.add((r, c))\n        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:\n            nr, nc = r + dr, c + dc\n            if 0 <= nr < m and 0 <= nc < n and (nr, nc) not in visited:\n                dfs(nr, nc, node, visited)\n        visited.remove((r, c))\n\n    for r in range(m):\n        for c in range(n):\n            dfs(r, c, trie, set())\n    print(\" \".join(sorted(res)))\n",
    "python_class": "class Solution:\n    def findWords(self, board: List[List[str]], words: List[str]) -> List[str]:\n        m, n = len(board), len(board[0])\n        trie = {}\n        for w in words:\n            cur = trie\n            for ch in w:\n                cur = cur.setdefault(ch, {})\n            cur['#'] = w\n        res = set()\n        def dfs(r, c, parent, visited):\n            ch = board[r][c]\n            if ch not in parent: return\n            node = parent[ch]\n            if '#' in node: res.add(node['#'])\n            visited.add((r, c))\n            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:\n                nr, nc = r + dr, c + dc\n                if 0 <= nr < m and 0 <= nc < n and (nr, nc) not in visited:\n                    dfs(nr, nc, node, visited)\n            visited.remove((r, c))\n        for r in range(m):\n            for c in range(n):\n                dfs(r, c, trie, set())\n        return sorted(list(res))\n",
    "java": "import java.util.*;\n\nclass Solution {\n    class TrieNode {\n        Map<Character, TrieNode> children = new HashMap<>();\n        String word = null;\n    }\n    public List<String> findWords(char[][] board, String[] words) {\n        TrieNode root = new TrieNode();\n        for (String w : words) {\n            TrieNode node = root;\n            for (char c : w.toCharArray()) {\n                node.children.putIfAbsent(c, new TrieNode());\n                node = node.children.get(c);\n            }\n            node.word = w;\n        }\n        Set<String> res = new TreeSet<>();\n        int m = board.length, n = board[0].length;\n        boolean[][] visited = new boolean[m][n];\n        for (int r = 0; r < m; r++) {\n            for (int c = 0; c < n; c++) {\n                dfs(board, r, c, root, visited, res);\n            }\n        }\n        return new ArrayList<>(res);\n    }\n    private void dfs(char[][] board, int r, int c, TrieNode node, boolean[][] visited, Set<String> res) {\n        if (r < 0 || r >= board.length || c < 0 || c >= board[0].length || visited[r][c]) return;\n        char ch = board[r][c];\n        if (!node.children.containsKey(ch)) return;\n        node = node.children.get(ch);\n        if (node.word != null) res.add(node.word);\n        visited[r][c] = true;\n        dfs(board, r + 1, c, node, visited, res);\n        dfs(board, r - 1, c, node, visited, res);\n        dfs(board, r, c + 1, node, visited, res);\n        dfs(board, r, c - 1, node, visited, res);\n        visited[r][c] = false;\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n#include <stdbool.h>\n#include <stdlib.h>\n\nint cmp(const void* a, const void* b) {\n    return strcmp(*(const char**)a, *(const char**)b);\n}\n\nint m, n;\nchar board[15][15];\nbool visited[15][15];\n\nbool search_word(int r, int c, const char* w, int idx) {\n    if (w[idx] == '\\0') return true;\n    if (r < 0 || r >= m || c < 0 || c >= n || visited[r][c] || board[r][c] != w[idx]) return false;\n    visited[r][c] = true;\n    int dr[] = {-1, 1, 0, 0};\n    int dc[] = {0, 0, -1, 1};\n    for (int d = 0; d < 4; d++) {\n        if (search_word(r + dr[d], c + dc[d], w, idx + 1)) {\n            visited[r][c] = false;\n            return true;\n        }\n    }\n    visited[r][c] = false;\n    return false;\n}\n\nint main() {\n    if (scanf(\"%d %d\", &m, &n) != 2) return 0;\n    for (int i = 0; i < m; i++) {\n        for (int j = 0; j < n; j++) {\n            scanf(\" %c\", &board[i][j]);\n        }\n    }\n    int k; scanf(\"%d\", &k);\n    char words[k][105];\n    char* found[k];\n    int found_count = 0;\n    for (int i = 0; i < k; i++) scanf(\"%s\", words[i]);\n\n    for (int w = 0; w < k; w++) {\n        bool ok = false;\n        for (int r = 0; r < m && !ok; r++) {\n            for (int c = 0; c < n && !ok; c++) {\n                memset(visited, 0, sizeof(visited));\n                if (search_word(r, c, words[w], 0)) {\n                    found[found_count++] = words[w];\n                    ok = true;\n                }\n            }\n        }\n    }\n    qsort(found, found_count, sizeof(char*), cmp);\n    for (int i = 0; i < found_count; i++) {\n        printf(\"%s%c\", found[i], (i == found_count - 1) ? '\\n' : ' ');\n    }\n    if (found_count == 0) printf(\"\\n\");\n    return 0;\n}"
  },
  "regular_expression_matching": {
    "python": "import sys\nlines = sys.stdin.read().splitlines()\ns = lines[0].strip() if len(lines) > 0 else \"\"\np = lines[1].strip() if len(lines) > 1 else \"\"\nm, n = len(s), len(p)\ndp = [[False] * (n + 1) for _ in range(m + 1)]\ndp[0][0] = True\nfor j in range(2, n + 1):\n    if p[j-1] == '*': dp[0][j] = dp[0][j-2]\nfor i in range(1, m + 1):\n    for j in range(1, n + 1):\n        if p[j-1] in (s[i-1], '.'):\n            dp[i][j] = dp[i-1][j-1]\n        elif p[j-1] == '*':\n            dp[i][j] = dp[i][j-2]\n            if p[j-2] in (s[i-1], '.'):\n                dp[i][j] = dp[i][j] or dp[i-1][j]\nprint(\"true\" if dp[m][n] else \"false\")\n",
    "python_class": "class Solution:\n    def isMatch(self, s: str, p: str) -> bool:\n        m, n = len(s), len(p)\n        dp = [[False] * (n + 1) for _ in range(m + 1)]\n        dp[0][0] = True\n        for j in range(2, n + 1):\n            if p[j-1] == '*': dp[0][j] = dp[0][j-2]\n        for i in range(1, m + 1):\n            for j in range(1, n + 1):\n                if p[j-1] in (s[i-1], '.'):\n                    dp[i][j] = dp[i-1][j-1]\n                elif p[j-1] == '*':\n                    dp[i][j] = dp[i][j-2]\n                    if p[j-2] in (s[i-1], '.'):\n                        dp[i][j] = dp[i][j] or dp[i-1][j]\n        return dp[m][n]\n",
    "java": "class Solution {\n    public boolean isMatch(String s, String p) {\n        int m = s.length(), n = p.length();\n        boolean[][] dp = new boolean[m + 1][n + 1];\n        dp[0][0] = true;\n        for (int j = 2; j <= n; j++) {\n            if (p.charAt(j - 1) == '*') dp[0][j] = dp[0][j - 2];\n        }\n        for (int i = 1; i <= m; i++) {\n            for (int j = 1; j <= n; j++) {\n                if (p.charAt(j - 1) == s.charAt(i - 1) || p.charAt(j - 1) == '.') {\n                    dp[i][j] = dp[i - 1][j - 1];\n                } else if (p.charAt(j - 1) == '*') {\n                    dp[i][j] = dp[i][j - 2];\n                    if (p.charAt(j - 2) == s.charAt(i - 1) || p.charAt(j - 2) == '.') {\n                        dp[i][j] = dp[i][j] || dp[i - 1][j];\n                    }\n                }\n            }\n        }\n        return dp[m][n];\n    }\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n#include <stdbool.h>\n\nint main() {\n    char s[105] = \"\", p[105] = \"\";\n    if (scanf(\"%s %s\", s, p) != 2) {\n        if (scanf(\"%s\", s) == 1) {}\n    }\n    int m = strlen(s), n = strlen(p);\n    bool dp[m + 1][n + 1];\n    memset(dp, 0, sizeof(dp));\n    dp[0][0] = true;\n    for (int j = 2; j <= n; j++) {\n        if (p[j-1] == '*') dp[0][j] = dp[0][j-2];\n    }\n    for (int i = 1; i <= m; i++) {\n        for (int j = 1; j <= n; j++) {\n            if (p[j-1] == s[i-1] || p[j-1] == '.') {\n                dp[i][j] = dp[i-1][j-1];\n            } else if (p[j-1] == '*') {\n                dp[i][j] = dp[i][j-2];\n                if (p[j-2] == s[i-1] || p[j-2] == '.') {\n                    dp[i][j] = dp[i][j] || dp[i-1][j];\n                }\n            }\n        }\n    }\n    printf(\"%s\\n\", dp[m][n] ? \"true\" : \"false\");\n    return 0;\n}"
  }
}

def get_all_solutions_for_problem(problem_id: str) -> Dict[str, str]:
    clean_id = (problem_id or "").strip().lower()
    return SOLUTIONS_REGISTRY.get(clean_id, {})
